// ============================================================================
// kontext init — interactive wizard for project setup
// ============================================================================

import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';

const TOKENS = ['USDC', 'USDT', 'DAI', 'EURC'] as const;
const CHAINS = ['base', 'ethereum', 'polygon', 'arbitrum', 'optimism', 'avalanche', 'arc'] as const;
const MODES = ['post-send', 'pre-send', 'both'] as const;
const ENVIRONMENTS = ['production', 'staging', 'development'] as const;

const SCREENING_PROVIDERS = ['built-in', 'chainalysis', 'trm', 'opensanctions'] as const;

// ---------------------------------------------------------------------------
// RPC provider presets
// ---------------------------------------------------------------------------

// Arc is testnet-only (mainnet targeting mid-2026). Placeholder RPC.
const DEFAULT_RPC: Record<string, string> = {
  base: 'https://mainnet.base.org',
  ethereum: 'https://eth.llamarpc.com',
  polygon: 'https://polygon-rpc.com',
  arbitrum: 'https://arb1.arbitrum.io/rpc',
  optimism: 'https://mainnet.optimism.io',
  avalanche: 'https://api.avax.network/ext/bc/C/rpc',
  arc: 'https://rpc.arc.network',
};

const ALCHEMY_RPC: Record<string, string> = {
  base: 'https://base-mainnet.g.alchemy.com/v2/{key}',
  ethereum: 'https://eth-mainnet.g.alchemy.com/v2/{key}',
  polygon: 'https://polygon-mainnet.g.alchemy.com/v2/{key}',
  arbitrum: 'https://arb-mainnet.g.alchemy.com/v2/{key}',
  optimism: 'https://opt-mainnet.g.alchemy.com/v2/{key}',
  avalanche: 'https://avax-mainnet.g.alchemy.com/v2/{key}',
};

const INFURA_RPC: Record<string, string> = {
  base: 'https://base-mainnet.infura.io/v3/{key}',
  ethereum: 'https://mainnet.infura.io/v3/{key}',
  polygon: 'https://polygon-mainnet.infura.io/v3/{key}',
  arbitrum: 'https://arbitrum-mainnet.infura.io/v3/{key}',
  optimism: 'https://optimism-mainnet.infura.io/v3/{key}',
  avalanche: 'https://avalanche-mainnet.infura.io/v3/{key}',
};

const RPC_PROVIDERS = ['public', 'alchemy', 'infura', 'custom'] as const;

// ---------------------------------------------------------------------------
// Zero-dep readline prompt
// ---------------------------------------------------------------------------

function createPrompt(): { ask: (q: string) => Promise<string>; close: () => void } {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return {
    ask: (question: string) =>
      new Promise<string>((resolve) => {
        rl.question(question, (answer) => resolve(answer.trim()));
      }),
    close: () => rl.close(),
  };
}

// ---------------------------------------------------------------------------
// Setup file generation
// ---------------------------------------------------------------------------

function generateSetupFile(
  mode: string,
  screeningProviders: string[],
  isTypeScript: boolean,
): string {
  const ext = isTypeScript ? 'ts' : 'js';
  const lines: string[] = [
    `// Auto-generated by \`npx kontext init\``,
  ];

  const byokProviders = screeningProviders.filter((p) => p !== 'built-in');
  const hasBYOK = byokProviders.length > 0;
  const isPreSend = mode === 'pre-send' || mode === 'both';

  // Build import list
  const imports: string[] = ['Kontext'];
  if (isPreSend) imports.push('withKontextCompliance');
  if (byokProviders.includes('chainalysis')) imports.push('ChainalysisFreeAPIProvider');
  if (byokProviders.includes('trm')) imports.push('TRMLabsProvider');
  if (byokProviders.includes('opensanctions')) imports.push('OpenSanctionsProvider');

  if (isPreSend) {
    lines.push(`// Import this file in your entry point to start compliance monitoring.`);
    lines.push(`// Wrap your viem client with withKontextCompliance for pre-send screening.`);
  } else {
    lines.push(`// Import this file in your entry point to start compliance monitoring.`);
  }

  lines.push(`import { ${imports.join(', ')} } from 'kontext-sdk';`);

  if (hasBYOK) {
    lines.push(`import config from './kontext.config.json'${isTypeScript ? ' with { type: "json" }' : ''};`);
  }

  lines.push('');

  // Build init call
  if (hasBYOK) {
    const providerLines: string[] = [];
    if (byokProviders.includes('chainalysis')) {
      providerLines.push(`    new ChainalysisFreeAPIProvider({ apiKey: config.screening.chainalysisApiKey })`);
    }
    if (byokProviders.includes('trm')) {
      providerLines.push(`    new TRMLabsProvider({ apiKey: config.screening.trmApiKey })`);
    }
    if (byokProviders.includes('opensanctions')) {
      providerLines.push(`    new OpenSanctionsProvider({ apiKey: config.screening.opensanctionsApiKey })`);
    }

    if (isPreSend) {
      lines.push(`export const kontext = Kontext.init({`);
    } else {
      lines.push(`Kontext.init({`);
    }
    lines.push(`  screening: {`);
    lines.push(`    providers: [`);
    lines.push(providerLines.join(',\n'));
    lines.push(`    ],`);
    lines.push(`    consensus: 'ANY_MATCH',`);
    lines.push(`  },`);
    lines.push(`});`);
  } else {
    if (isPreSend) {
      lines.push(`export const kontext = Kontext.init();`);
    } else {
      lines.push(`Kontext.init();`);
    }
  }

  if (isPreSend) {
    lines.push(`export { withKontextCompliance };`);
  }

  lines.push('');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

export async function runInit(opts: { json: boolean }): Promise<void> {
  const configPath = path.join(process.cwd(), 'kontext.config.json');

  if (fs.existsSync(configPath)) {
    if (!opts.json) {
      process.stdout.write('\n  kontext.config.json already exists in this directory.\n');
      process.stdout.write('  Delete it first to re-initialize.\n\n');
    } else {
      process.stdout.write(JSON.stringify({ error: 'kontext.config.json already exists' }) + '\n');
    }
    return;
  }

  if (opts.json) {
    // Non-interactive mode: output a template
    const template = {
      $schema: 'https://getkontext.com/schema/config.json',
      projectId: 'my-project',
      agentId: 'my-agent',
      environment: 'production',
      wallets: [],
      tokens: ['USDC'],
      chains: ['base'],
      rpcEndpoints: { base: DEFAULT_RPC['base'] },
      mode: 'post-send',
    };
    fs.writeFileSync(configPath, JSON.stringify(template, null, 2) + '\n');
    process.stdout.write(JSON.stringify({ created: configPath, config: template }) + '\n');
    return;
  }

  const { ask, close } = createPrompt();

  try {
    process.stdout.write('\n  Kontext — compliance logging for agents that move money\n\n');

    // Project name
    const projectId = (await ask('  ? Project name: ')) || 'my-project';

    // Agent ID
    const agentId = (await ask('  ? Agent ID: ')) || `${projectId}-agent`;

    // Wallet addresses
    const walletsRaw = await ask('  ? Wallet addresses to monitor (comma-separated, or skip): ');
    const wallets = walletsRaw
      ? walletsRaw.split(',').map((w) => w.trim()).filter(Boolean)
      : [];

    // Tokens
    process.stdout.write(`  ? Which tokens? [${TOKENS.join(', ')}]\n`);
    const tokensRaw = (await ask('    (comma-separated, default: USDC): ')) || 'USDC';
    const tokens = tokensRaw
      .split(',')
      .map((t) => t.trim().toUpperCase())
      .filter((t) => (TOKENS as readonly string[]).includes(t));
    if (tokens.length === 0) tokens.push('USDC');

    // Chains
    process.stdout.write(`  ? Which chains? [${CHAINS.join(', ')}]\n`);
    const chainsRaw = (await ask('    (comma-separated, default: base): ')) || 'base';
    const chains = chainsRaw
      .split(',')
      .map((c) => c.trim().toLowerCase())
      .filter((c) => (CHAINS as readonly string[]).includes(c));
    if (chains.length === 0) chains.push('base');

    // Mode
    process.stdout.write('  ? Compliance mode:\n');
    process.stdout.write('    post-send  — log after tx, never blocks (recommended)\n');
    process.stdout.write('    pre-send   — screen before tx, blocks if non-compliant\n');
    process.stdout.write('    both       — pre-send screening + post-send logging\n');
    const modeRaw = (await ask('    (default: post-send): ')) || 'post-send';
    const mode = (MODES as readonly string[]).includes(modeRaw) ? modeRaw : 'post-send';

    // RPC provider selection (only when wallets configured)
    const rpcEndpoints: Record<string, string> = {};
    if (wallets.length > 0) {
      process.stdout.write('\n  ? RPC provider:\n');
      process.stdout.write('      public   — free, rate-limited (default)\n');
      process.stdout.write('      alchemy  — requires API key\n');
      process.stdout.write('      infura   — requires API key (MetaMask default)\n');
      process.stdout.write('      custom   — enter URLs per chain\n');
      const rpcProviderRaw = (await ask('    (default: public): ')) || 'public';
      const rpcProvider = (RPC_PROVIDERS as readonly string[]).includes(rpcProviderRaw)
        ? rpcProviderRaw
        : 'public';

      if (rpcProvider === 'public') {
        for (const chain of chains) {
          const rpc = DEFAULT_RPC[chain];
          if (rpc) rpcEndpoints[chain] = rpc;
        }
      } else if (rpcProvider === 'alchemy' || rpcProvider === 'infura') {
        const providerMap = rpcProvider === 'alchemy' ? ALCHEMY_RPC : INFURA_RPC;
        const providerName = rpcProvider === 'alchemy' ? 'Alchemy' : 'Infura';
        const apiKey = await ask(`  ? ${providerName} API key: `);

        for (const chain of chains) {
          const template = providerMap[chain];
          if (template && apiKey) {
            rpcEndpoints[chain] = template.replace('{key}', apiKey);
          } else {
            // Fall back to public RPC for unsupported chains (e.g., Arc)
            const fallback = DEFAULT_RPC[chain];
            if (fallback) rpcEndpoints[chain] = fallback;
          }
        }
      } else {
        // custom — prompt per chain (original behavior)
        process.stdout.write('\n  RPC endpoints (needed for wallet monitoring):\n');
        for (const chain of chains) {
          const defaultRpc = DEFAULT_RPC[chain] ?? '';
          const rpc = (await ask(`  ? RPC for ${chain} (default: ${defaultRpc}): `)) || defaultRpc;
          if (rpc) rpcEndpoints[chain] = rpc;
        }
      }
    }

    // Countries (optional)
    process.stdout.write('\n');
    const fromCountry = await ask('  ? From country (optional, for corridor compliance): ');
    const toCountry = await ask('  ? To country (optional): ');

    // Environment
    const envRaw = (await ask(`  ? Environment [${ENVIRONMENTS.join('/')}] (default: production): `)) || 'production';
    const environment = (ENVIRONMENTS as readonly string[]).includes(envRaw) ? envRaw : 'production';

    // Screening providers (multi-select)
    process.stdout.write('\n  ? Screening providers (comma-separated, or skip):\n');
    process.stdout.write('      built-in       — free, limited (~40 addresses, ~19K entities)\n');
    process.stdout.write('      chainalysis    — free API key (address screening, all chains)\n');
    process.stdout.write('      trm            — free API key (address screening, 25 chains)\n');
    process.stdout.write('      opensanctions  — paid API key (address + entity, 290K+ entities)\n');
    const screeningRaw = (await ask('    (default: built-in): ')) || 'built-in';
    const screeningSelections = screeningRaw === 'skip'
      ? []
      : screeningRaw
          .split(',')
          .map((s) => s.trim().toLowerCase())
          .filter((s) => (SCREENING_PROVIDERS as readonly string[]).includes(s));
    if (screeningSelections.length === 0 && screeningRaw !== 'skip') {
      screeningSelections.push('built-in');
    }

    // Collect API keys for selected BYOK providers
    const screeningConfig: Record<string, unknown> = {};
    const byokProviders = screeningSelections.filter((s) => s !== 'built-in');

    if (byokProviders.length > 0) {
      process.stdout.write('\n');
      if (byokProviders.includes('chainalysis')) {
        const key = await ask('  ? Chainalysis API key: ');
        if (key) screeningConfig['chainalysisApiKey'] = key;
      }
      if (byokProviders.includes('trm')) {
        const key = await ask('  ? TRM Labs API key: ');
        if (key) screeningConfig['trmApiKey'] = key;
      }
      if (byokProviders.includes('opensanctions')) {
        const key = await ask('  ? OpenSanctions API key: ');
        if (key) screeningConfig['opensanctionsApiKey'] = key;
      }
    }

    // Build config
    const config: Record<string, unknown> = {
      $schema: 'https://getkontext.com/schema/config.json',
      projectId,
      agentId,
      environment,
      wallets,
      tokens,
      chains,
      mode,
    };

    if (Object.keys(rpcEndpoints).length > 0) {
      config['rpcEndpoints'] = rpcEndpoints;
    }

    if (fromCountry || toCountry) {
      const corridors: Record<string, string> = {};
      if (fromCountry) corridors['from'] = fromCountry;
      if (toCountry) corridors['to'] = toCountry;
      config['corridors'] = corridors;
    }

    if (screeningSelections.length > 0) {
      config['screening'] = {
        providers: screeningSelections,
        ...screeningConfig,
      };
    }

    // Write config file
    fs.writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n');

    // Create .kontext directory
    const kontextDir = path.join(process.cwd(), '.kontext');
    if (!fs.existsSync(kontextDir)) {
      fs.mkdirSync(kontextDir, { recursive: true });
    }

    // Generate kontext setup file
    const isTypeScript = fs.existsSync(path.join(process.cwd(), 'tsconfig.json'));
    const setupExt = isTypeScript ? 'ts' : 'js';
    const setupPath = path.join(process.cwd(), `kontext.${setupExt}`);
    const setupContent = generateSetupFile(mode, screeningSelections, isTypeScript);
    fs.writeFileSync(setupPath, setupContent);

    // Summary
    process.stdout.write('\n');
    process.stdout.write('  ✓ Created kontext.config.json\n');
    process.stdout.write(`  ✓ Created kontext.${setupExt}\n`);
    process.stdout.write('  ✓ Created .kontext/ directory\n');
    if (wallets.length > 0) {
      process.stdout.write(`  ✓ Monitoring ${wallets.length} wallet${wallets.length > 1 ? 's' : ''} on ${chains.join(', ')}\n`);
    }
    process.stdout.write(`  ✓ Tokens: ${tokens.join(', ')}\n`);
    process.stdout.write(`  ✓ Mode: ${mode}\n`);
    if (screeningSelections.length > 0) {
      process.stdout.write(`  ✓ Screening: ${screeningSelections.join(', ')}\n`);
    }

    // Coverage warning for built-in only
    if (screeningSelections.includes('built-in') && byokProviders.length === 0) {
      process.stdout.write('\n  ⚠ Built-in screening covers ~3% of OFAC crypto addresses.\n');
      process.stdout.write('    For production, consider adding a screening provider key.\n');
    }

    // Mode-aware integration message
    const isPreSend = mode === 'pre-send' || mode === 'both';
    process.stdout.write('\n  Add to your entry file:\n\n');
    if (isPreSend) {
      process.stdout.write("    import { kontext, withKontextCompliance } from './kontext'\n");
      process.stdout.write('    const client = withKontextCompliance(rawClient, kontext)\n');
    } else {
      process.stdout.write("    import './kontext'\n");
    }

    process.stdout.write("\n  You're ready to Kontext!\n\n");
  } finally {
    close();
  }
}
