import type { Metadata } from "next";
import { Badge } from "@/components/ui/badge";
import { CodeBlock } from "@/components/code-block";
import { Separator } from "@/components/ui/separator";
import { BookOpen, Zap, Code2, Shield } from "lucide-react";

export const metadata: Metadata = {
  title: "Documentation",
  description:
    "The trust layer for agentic stablecoin and fiat payments. One command, one line of code — cryptographic verifiable intent for every payment your org makes.",
};

const installCode = `npm install kontext-sdk`;

const pythonInstallCode = `pip install kontext-sdk`;

const pythonQuickStartCode = `from kontext import Kontext

ctx = Kontext(api_key="sk_...", project_id="my-agent")

# Log a transaction
ctx.log_transaction(
    tx_hash="0xabc...",
    chain="base",
    amount="5000",
    token="USDC",
    from_address="0xsender...",
    to_address="0xrecipient...",
    agent_id="payment-agent",
)

# Trust score
trust = ctx.get_trust_score("payment-agent")
print(f"Trust: {trust.score}/100 ({trust.level})")

# Human-in-the-loop
task = ctx.create_task(
    description="Approve $5K transfer",
    agent_id="payment-agent",
    required_evidence=["txHash"],
)
confirmed = ctx.confirm_task(task.id, evidence={"txHash": "0xabc..."})

# Export audit trail
audit = ctx.export_audit(format="json")

# Flush to server
ctx.flush()`;

const pythonAsyncCode = `from kontext import AsyncKontext

async with AsyncKontext(api_key="sk_...", project_id="my-agent") as ctx:
    await ctx.log(action="transfer", agent_id="agent-1")
    trust = await ctx.get_trust_score("agent-1")
    print(f"Trust: {trust.score}/100")`;

const quickStartCode = `import { Kontext, withKontextCompliance } from 'kontext-sdk';
import { createWalletClient, http } from 'viem';
import { base } from 'viem/chains';

// Reads kontext.config.json (generated by npx kontext init)
const kontext = Kontext.init();

// Wrap your viem client — one line
const client = withKontextCompliance(
  createWalletClient({ chain: base, transport: http() }),
  kontext,
);

// Every stablecoin transfer is now auto-verified
await client.sendTransaction({ to: usdcAddress, data: transferCalldata });
// → OFAC screening, audit trail, trust score — automatically`;

const explicitVerifyCode = `import { Kontext } from 'kontext-sdk';

const ctx = Kontext.init({ projectId: 'my-project' });

// Explicit verify for individual transactions
const result = await ctx.verify({
  txHash: '0xabc...def',
  chain: 'base',
  amount: '5000',
  token: 'USDC',
  from: '0xAgentWallet',
  to: '0xRecipient',
  agentId: 'payment-agent',
});

// result.compliant — true/false
// result.checks — OFAC, Travel Rule, CTR thresholds
// result.riskLevel — low | medium | high | critical
// result.digestProof — tamper-evident SHA-256 chain`;

const autoInstrumentationCode = `# Step 1: Run the CLI wizard
$ npx kontext init

  ? Project name: treasury-agent
  ? Agent ID: treasury-agent-v1
  ? Wallet addresses to monitor: 0xTreasury..., 0xAgent...
  ? Which tokens? USDC, USDT
  ? Which chains? base, ethereum
  ? Compliance mode: post-send
  ? RPC for base: https://mainnet.base.org
  ? From country (optional): US

  ✓ Created kontext.config.json
  ✓ Monitoring 2 wallets on base, ethereum`;

const autoInstrumentationCodeTS = `import { Kontext, withKontextCompliance } from 'kontext-sdk';

// Step 2: Zero-arg init reads kontext.config.json automatically
const kontext = Kontext.init();

// Step 3: Wrap your viem client — 1 line
const client = withKontextCompliance(rawClient, kontext);

// Every stablecoin transfer is now auto-logged with:
// - OFAC screening
// - Tamper-evident audit trail
// - Trust scoring
// - Digest chain proof

// Wallet monitoring also runs in the background —
// catches transfers from ANY source (other scripts, wallet UIs, etc.)`;

const autoInstrumentationConfigCode = `// kontext.config.json (generated by npx kontext init)
{
  "$schema": "https://getkontext.com/schema/config.json",
  "projectId": "treasury-agent",
  "agentId": "treasury-agent-v1",
  "environment": "production",
  "wallets": ["0xTreasury...", "0xAgent..."],
  "tokens": ["USDC", "USDT"],
  "chains": ["base", "ethereum"],
  "rpcEndpoints": {
    "base": "https://mainnet.base.org",
    "ethereum": "https://eth.llamarpc.com"
  },
  "mode": "post-send",
  "corridors": { "from": "US" }
}`;

const actionLoggingCode = `import { Kontext } from 'kontext-sdk';

const ctx = Kontext.init({ projectId: 'my-project' });

// Log any agent action -- not just transfers
await ctx.log({
  action: 'data_access',
  agentId: 'research-agent',
  details: 'Queried customer database',
  metadata: { purpose: 'quarterly_report' },
});

// Log agent reasoning separately
// When regulators ask "why did your agent do that?" -- you can answer
await ctx.logReasoning({
  agentId: 'payment-agent-v2',
  action: 'approve-transfer',
  reasoning: 'Transfer within daily limit. Recipient verified in allowlist.',
  confidence: 0.95,
  context: { dailyTotal: '32000', recipientVerified: true },
});

// Retrieve reasoning entries later
const entries = ctx.getReasoningEntries('payment-agent-v2');`;

const taskConfirmationCode = `import { Kontext } from 'kontext-sdk';

const ctx = Kontext.init({ projectId: 'treasury-app' });

// Create a task that requires human approval
const task = await ctx.createTask({
  description: 'Approve $25,000 USDC transfer to 0xrecipient',
  agentId: 'treasury-agent-v2',
  requiredEvidence: ['txHash', 'recipientVerified'],
});

// ... human reviews and approves ...

// Confirm with evidence
const confirmed = await ctx.confirmTask({
  taskId: task.id,
  evidence: {
    txHash: '0xabc...def',
    recipientVerified: true,
  },
  confirmedBy: 'admin@company.com',
});

// Check task status at any time
const status = await ctx.getTaskStatus(task.id);

// List all pending tasks
const pending = ctx.getTasks('pending');`;

const auditExportCode = `import { Kontext } from 'kontext-sdk';

const ctx = Kontext.init({ projectId: 'my-project' });

// ... log some actions and transactions ...

// Export the full audit trail as JSON
const audit = await ctx.export({ format: 'json' });
// audit.data contains all action logs with digest proofs

// Verify the digest chain is intact (no tampering)
const chain = ctx.verifyDigestChain();
console.log('Chain valid:', chain.valid);
console.log('Chain length:', chain.chainLength);

// Get the terminal digest -- your tamper-evident fingerprint
const terminal = ctx.getTerminalDigest();

// Export the full digest chain for external verification
const exported = ctx.exportDigestChain();
// { genesisHash, links, terminalDigest }

// Generate a compliance certificate (includes digest proof + trust score)
const cert = await ctx.generateComplianceCertificate({
  agentId: 'treasury-agent-v2',
  timeRange: { from: startOfMonth, to: endOfMonth },
  includeReasoning: true,
});`;

const trustScoringCode = `import { Kontext } from 'kontext-sdk';

const ctx = Kontext.init({ projectId: 'my-project' });

// Get trust score for any agent
const trust = await ctx.getTrustScore('payment-agent-v2');

console.log(trust.score);   // 87 (0-100)
console.log(trust.level);   // 'high'
console.log(trust.factors);
// {
//   history: 0.95,       -- agent's track record
//   amount: 0.88,        -- transaction amount patterns
//   frequency: 0.92,     -- how often the agent transacts
//   destination: 0.85,   -- recipient trust level
//   behavior: 0.90,      -- behavioral consistency
// }

// Evaluate a transaction before executing it
const evaluation = await ctx.evaluateTransaction({
  txHash: '0xabc...def',
  chain: 'base',
  amount: '15000',
  token: 'USDC',
  from: '0xsender...',
  to: '0xrecipient...',
  agentId: 'payment-agent-v2',
});`;

const anomalyDetectionCode = `import { Kontext } from 'kontext-sdk';

const ctx = Kontext.init({ projectId: 'my-project' });

// Enable anomaly detection with rules
ctx.enableAnomalyDetection({
  rules: ['unusualAmount', 'frequencySpike'],
  thresholds: {
    maxAmount: '50000',
    maxFrequency: 20,
  },
});

// React to anomalies in real time
const unsubscribe = ctx.onAnomaly((event) => {
  console.log('Anomaly detected:', event.type);
  console.log('Details:', event.details);
  // Alert your compliance team via Slack, PagerDuty, etc.
});

// verify() automatically checks anomaly rules
const result = await ctx.verify({
  txHash: '0xabc...def',
  chain: 'base',
  amount: '75000',
  token: 'USDC',
  from: '0xsender...',
  to: '0xrecipient...',
  agentId: 'payment-agent-v2',
});

// Turn it off when you don't need it
ctx.disableAnomalyDetection();`;

const onChainAnchoringCode = `import { Kontext, verifyAnchor, getAnchor, anchorDigest } from 'kontext-sdk';

const ctx = Kontext.init({ projectId: 'my-project' });

// Option 1: Anchor automatically via verify()
const result = await ctx.verify({
  txHash: '0xabc...def',
  chain: 'base',
  amount: '5000',
  token: 'USDC',
  from: '0xsender...',
  to: '0xrecipient...',
  agentId: 'payment-agent-v2',
  anchor: {
    rpcUrl: 'https://mainnet.base.org',
    contractAddress: process.env.KONTEXT_ANCHOR_ADDRESS,
    privateKey: process.env.ANCHOR_PRIVATE_KEY,
  },
});
// result.anchorProof = { txHash, blockNumber, chain, ... }

// Option 2: Read-only verification -- zero dependencies
const verified = await verifyAnchor(rpcUrl, contractAddress, digest);
// verified.anchored = true/false

// Option 3: Get full anchor details
const details = await getAnchor(rpcUrl, contractAddress, digest);
// details = { anchorer, projectHash, timestamp }

// Option 4: Write an anchor manually (requires viem as peer dep)
const anchorResult = await anchorDigest(
  { rpcUrl, contractAddress, privateKey },
  digest,
  'my-project'
);`;

const a2aAttestationCode = `import { Kontext, fetchAgentCard, exchangeAttestation } from 'kontext-sdk';

const ctx = Kontext.init({ projectId: 'my-project' });

// Option 1: Attestation via verify()
const result = await ctx.verify({
  txHash: '0xabc...def',
  chain: 'base',
  amount: '5000',
  token: 'USDC',
  from: '0xsender...',
  to: '0xrecipient...',
  agentId: 'sender-agent',
  counterparty: {
    endpoint: 'https://receiver.example.com',
    agentId: 'receiver-v1',
  },
});
// result.counterparty = { attested, digest, agentId, timestamp }

// Option 2: Discover a counterparty agent
const card = await fetchAgentCard('https://receiver.example.com');
// card = { agentId, kontextVersion, capabilities, attestEndpoint }

// Option 3: Exchange attestation directly
const attestation = await exchangeAttestation(
  { endpoint: 'https://receiver.example.com', agentId: 'receiver-v1' },
  {
    senderDigest: ctx.getTerminalDigest(),
    senderAgentId: 'sender-agent',
    amount: '5000',
    token: 'USDC',
    timestamp: new Date().toISOString(),
  }
);`;

const agentProvenanceCode = `import { Kontext, FileStorage } from 'kontext-sdk';

const ctx = Kontext.init({
  projectId: 'treasury-app',
  storage: new FileStorage('.kontext'),
});

// Layer 1: Session delegation — record who authorized the agent
const session = await ctx.createAgentSession({
  agentId: 'treasury-agent',
  delegatedBy: 'user:vinay',
  scope: ['transfer', 'approve'],
  expiresAt: new Date(Date.now() + 3600_000).toISOString(),
});

// Layer 2: Action binding — every verify() call ties to the session
const result = await ctx.verify({
  txHash: '0xabc...def',
  chain: 'base',
  amount: '5000',
  token: 'USDC',
  from: '0xAgentWallet',
  to: '0xRecipient',
  agentId: 'treasury-agent',
  sessionId: session.sessionId,
});

// Layer 3: Human attestation — reviewer signs off
const checkpoint = await ctx.createCheckpoint({
  sessionId: session.sessionId,
  actionIds: [result.transaction.id],
  summary: 'Reviewed $5K USDC transfer to known vendor',
});

// Attest with a key the agent never touches
const attested = await ctx.attestCheckpoint({
  checkpointId: checkpoint.checkpointId,
  attestedBy: 'compliance-officer@company.com',
  signature: reviewerSignature,
});

// End the session when done
await ctx.endAgentSession(session.sessionId);

// List all sessions and checkpoints
const sessions = ctx.getAgentSessions('treasury-agent');
const checkpoints = ctx.getCheckpoints(session.sessionId);`;

const apiReferenceCode = `// Initialization
const ctx = Kontext.init(config: KontextConfig): Kontext;

// The main function -- compliance check + transaction log in one call
await ctx.verify(input: VerifyInput): Promise<VerifyResult>;

// Action logging
await ctx.log(input: LogActionInput): Promise<ActionLog>;
await ctx.logTransaction(input: LogTransactionInput): Promise<TransactionRecord>;
await ctx.logReasoning(input: LogReasoningInput): Promise<ReasoningEntry>;
ctx.getReasoningEntries(agentId: string): ReasoningEntry[];
await ctx.flushLogs(): Promise<void>;

// Task confirmation (human-in-the-loop)
await ctx.createTask(input: CreateTaskInput): Promise<Task>;
await ctx.confirmTask(input: ConfirmTaskInput): Promise<Task>;
await ctx.getTaskStatus(taskId: string): Promise<Task | undefined>;
await ctx.startTask(taskId: string): Promise<Task>;
await ctx.failTask(taskId: string, reason: string): Promise<Task>;
ctx.getTasks(status?: TaskStatus): Task[];

// Trust scoring
await ctx.getTrustScore(agentId: string): Promise<TrustScore>;
await ctx.evaluateTransaction(tx: LogTransactionInput): Promise<TransactionEvaluation>;

// Anomaly detection
ctx.enableAnomalyDetection(config: AnomalyDetectionConfig): void;
ctx.disableAnomalyDetection(): void;
ctx.onAnomaly(callback: AnomalyCallback): () => void;

// Audit export
await ctx.export(options: ExportOptions): Promise<ExportResult>;
await ctx.generateReport(options: ReportOptions): Promise<ComplianceReport>;
await ctx.generateComplianceCertificate(input): Promise<ComplianceCertificate>;

// Digest chain (tamper-evidence)
ctx.getTerminalDigest(): string;
ctx.verifyDigestChain(): DigestVerification;
ctx.exportDigestChain(): { genesisHash, links, terminalDigest };
ctx.getActions(): ActionLog[];

// Agent provenance
await ctx.createAgentSession(input: CreateAgentSessionInput): Promise<AgentSession>;
await ctx.endAgentSession(sessionId: string): Promise<AgentSession>;
ctx.getAgentSessions(agentId: string): AgentSession[];
await ctx.createCheckpoint(input: CreateCheckpointInput): Promise<Checkpoint>;
await ctx.attestCheckpoint(input: AttestCheckpointInput): Promise<Checkpoint>;
ctx.getCheckpoints(sessionId: string): Checkpoint[];

// Persistence
await ctx.flush(): Promise<void>;
await ctx.restore(): Promise<void>;

// Plan management
ctx.getUsage(): PlanUsage;
ctx.setPlan(tier: PlanTier): void;
ctx.onUsageWarning(callback): () => void;
ctx.onLimitReached(callback): () => void;

// Lifecycle
await ctx.destroy(): Promise<void>;`;

const configCode = `import { Kontext, FileStorage } from 'kontext-sdk';

const ctx = Kontext.init({
  // Required
  projectId: 'my-project',

  // Optional
  environment: 'production',  // 'development' | 'staging' | 'production'
  apiKey: 'sk_live_...',      // only needed for cloud mode
  plan: 'free',               // 'free' | 'payg' | 'enterprise'

  // Persistence -- default is in-memory (resets on restart)
  storage: new FileStorage('./compliance-data'),

  // Event exporters -- where to send events
  exporters: [
    // new ConsoleExporter(),       // prints to stdout (dev)
    // new JsonFileExporter(path),  // writes JSONL to disk
    // new HttpExporter(config),    // sends to any HTTP endpoint
    // new KontextCloudExporter(),  // ships to api.getkontext.com (payg)
  ],
});`;

const typesCode = `import type {
  // Core
  KontextConfig,
  KontextMode,
  LogActionInput,
  LogTransactionInput,
  TransactionRecord,
  ActionLog,

  // Verify
  VerifyInput,
  VerifyResult,

  // Tasks
  Task,
  CreateTaskInput,
  ConfirmTaskInput,

  // Trust & Anomaly
  TrustScore,
  AnomalyEvent,
  AnomalyDetectionConfig,

  // Export & Reports
  ExportOptions,
  ExportResult,
  ComplianceReport,
  DigestVerification,

  // Reasoning & Certificates
  ReasoningEntry,
  ComplianceCertificate,

  // On-chain anchoring
  OnChainAnchorConfig,
  AnchorResult,
  AnchorVerification,

  // A2A attestation
  AgentCard,
  CounterpartyConfig,
  AttestationRequest,
  AttestationResponse,
  CounterpartyAttestation,

  // Agent provenance
  AgentSession,
  CreateAgentSessionInput,
  Checkpoint,
  CreateCheckpointInput,
  AttestCheckpointInput,
} from 'kontext-sdk';`;

const agentIdentityCode = `import { Kontext } from 'kontext-sdk';

const ctx = Kontext.init({
  apiKey: process.env.KONTEXT_KEY,
  projectId: 'forensics',
  plan: 'payg',
});

// Register an agent with wallet mappings
ctx.registerAgentIdentity({
  agentId: 'treasury-agent-v2',
  displayName: 'Treasury Agent',
  entityType: 'autonomous',  // 'autonomous' | 'semi-autonomous' | 'human-supervised'
  wallets: [
    { address: '0xTreasury...abc', chain: 'base', label: 'primary' },
    { address: '0xReserve...def', chain: 'base', label: 'reserve' },
  ],
});

// Add a wallet later
ctx.addAgentWallet('treasury-agent-v2', {
  address: '0xOps...ghi', chain: 'ethereum', label: 'operations',
});

// Reverse lookup: which agent owns this wallet?
const agent = ctx.lookupAgentByWallet('0xTreasury...abc');
console.log(agent?.agentId); // 'treasury-agent-v2'

// Retrieve identity
const identity = ctx.getAgentIdentity('treasury-agent-v2');`;

const walletClusteringCode = `import { Kontext } from 'kontext-sdk';

const ctx = Kontext.init({
  apiKey: process.env.KONTEXT_KEY,
  projectId: 'forensics',
  plan: 'payg',
});

// Register agents and their wallets...
// Then detect clusters across all registered agents
const clusters = ctx.getWalletClusters();

for (const cluster of clusters) {
  console.log('Cluster wallets:', cluster.wallets);
  console.log('Heuristics matched:', cluster.heuristics);
  // e.g. ['shared-owner', 'funding-chain', 'temporal-correlation']
  console.log('Evidence:', cluster.evidence);
}

// 5 clustering heuristics:
// - shared-owner: wallets registered to the same agent
// - temporal-correlation: wallets active in the same time windows
// - funding-chain: one wallet funds another
// - amount-pattern: matching transaction amounts across wallets
// - network-overlap: shared counterparties`;

const confidenceScoringCode = `import { Kontext } from 'kontext-sdk';

const ctx = Kontext.init({
  apiKey: process.env.KONTEXT_KEY,
  projectId: 'forensics',
  plan: 'payg',
});

// Compute identity confidence for an agent
const score = ctx.getKYAConfidenceScore('treasury-agent-v2');

console.log(score.score);      // 82 (0-100)
console.log(score.level);      // 'high' | 'medium' | 'low' | 'very-low'
console.log(score.components); // breakdown by factor

// Components: identity-completeness, wallet-verification,
//             behavioral-consistency, historical-depth, cluster-coherence

// Export all forensics data
const envelope = ctx.getKYAExport();
// { identities, clusters, embeddings, links, scores, generatedAt }`;

const walletProviderConfigCode = `// kontext.config.json — generated by "kontext init"
{
  "projectId": "my-agent",
  "walletProvider": {
    "type": "circle",
    "apiKeyEnvVar": "CIRCLE_API_KEY",
    "entitySecretEnvVar": "CIRCLE_ENTITY_SECRET",
    "circleEnvironment": "production",
    "secretsStorage": { "type": "dotenv", "path": ".env" }
  }
}`;

const walletProviderCircleCode = `import { Kontext, CircleWalletManager } from 'kontext-sdk';

// Option 1: Auto-configured from kontext.config.json
const ctx = Kontext.init();
const walletSet = await ctx.createCircleWalletSet({ name: 'treasury' });
const wallets = await ctx.createCircleWallet({
  walletSetId: walletSet.id,
  blockchains: ['base'],
});

// Transfer with automatic compliance verification
const result = await ctx.circleTransferWithCompliance({
  walletId: wallets[0].id,
  tokenAddress: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
  destinationAddress: '0xRecipient...',
  amount: '5000',
  blockchain: 'base',
  agentId: 'treasury-agent',
});
// result.complianceResult.compliant = true/false
// result.state = 'INITIATED' | 'BLOCKED'

// Option 2: Direct manager (no Kontext client)
const mgr = new CircleWalletManager({
  apiKey: process.env.CIRCLE_API_KEY!,
  entitySecret: process.env.CIRCLE_ENTITY_SECRET!,
});
const valid = await mgr.validateCredentials(); // true/false`;

const walletProviderCoinbaseCode = `import { Kontext, CoinbaseWalletManager } from 'kontext-sdk';

const ctx = Kontext.init(); // loads walletProvider from config

// Create an EVM account
const account = await ctx.createCoinbaseAccount({ network: 'base' });

// Transfer with compliance
const result = await ctx.coinbaseTransferWithCompliance({
  fromAddress: account.address,
  toAddress: '0xRecipient...',
  amount: '1000',
  token: 'USDC',
  network: 'base',
  agentId: 'payment-agent',
});

// Direct manager usage
const mgr = new CoinbaseWalletManager({
  apiKeyId: process.env.CDP_API_KEY_ID!,
  apiKeySecret: process.env.CDP_API_KEY_SECRET!,
  walletSecret: process.env.CDP_WALLET_SECRET!,
});
const accounts = await mgr.listAccounts();`;

const walletProviderMetaMaskCode = `import { Kontext, MetaMaskWalletManager } from 'kontext-sdk';

const ctx = Kontext.init(); // loads walletProvider from config

// Connect with JWT auth
const account = await ctx.metamaskConnect(userIdToken);

// Transfer with compliance
const result = await ctx.metamaskTransferWithCompliance({
  toAddress: '0xRecipient...',
  amount: '500',
  token: 'USDC',
  chain: 'base',
  idToken: userIdToken,
  agentId: 'wallet-agent',
});

// Direct manager usage (requires @web3auth/node-sdk)
const mgr = new MetaMaskWalletManager({
  clientId: process.env.METAMASK_CLIENT_ID!,
  authConnectionId: 'my-auth-connection',
  web3AuthNetwork: 'sapphire_mainnet',
});`;

const cliInstallCode = `# Install globally
npm install -g @kontext-sdk/cli

# Or run directly with npx (no install)
npx @kontext-sdk/cli verify --chain base --amount 0.50

# Verify installation
kontext --version  # 0.12.0`;

const cliCommandsCode = `# Initialize project — interactive wizard
kontext init

# Static compliance check (no digest chain)
kontext check --chain base --amount 0.50 --from 0xSender --to 0xRecipient

# Full verification with digest chain and trust scoring
kontext verify --chain base --amount 0.50 --token USDC \\
  --from 0xSender --to 0xRecipient --agent research-agent

# Log agent reasoning
kontext reason --agent payment-agent-v2 \\
  --action approve-transfer \\
  --reasoning "Within daily limit. Recipient verified."

# Generate compliance certificate
kontext cert --agent payment-agent-v2 --format json

# Export audit trail
kontext audit --format json --output ./audit-trail.json

# Anchor digest on-chain (Base mainnet)
kontext anchor --rpc https://mainnet.base.org --contract 0x8972...a86

# Anchor digest on-chain (Base Sepolia testnet)
kontext anchor --rpc https://sepolia.base.org --contract 0xbc71...b46

# Exchange A2A attestation
kontext attest --endpoint https://counterparty.example.com

# Sync OFAC SDN list
kontext sync --list ofac

# Manage agent sessions and checkpoints
kontext session create --agent treasury-agent --scope transfer,approve
kontext checkpoint create --session <sessionId> --summary "Reviewed batch"

# Reserve reconciliation — query on-chain supply
kontext reconcile --token USDC --chain base --rpc https://mainnet.base.org \\
  --published 36241612000 --tolerance 0.001 --agent treasury-bot

# Authenticate CLI (stores API key in OS keychain)
kontext login`;

const reserveReconciliationCode = `import { ReserveReconciler } from 'kontext-sdk';

const snapshot = await ReserveReconciler.querySupply({
  token: 'USDC',
  chain: 'base',
  rpcUrl: process.env.BASE_RPC_URL!,
  publishedReserves: '36241612000',  // from issuer report
  tolerance: 0.001,                   // 0.1%
});

// snapshot.reconciliationStatus
//   → 'matched' | 'delta_within_tolerance' | 'discrepancy' | 'unverified'
// snapshot.onChainSupply      → '36241847291'
// snapshot.snapshotBlockNumber → 28419032
// snapshot.snapshotBlockHash  → '0x8f2a...d41c'
// snapshot.delta              → '0.0000064...' (raw ratio)`;

const reserveReconciliationClientCode = `// Via the Kontext client (logs to digest chain automatically)
const snapshot = await kontext.logReserveSnapshot({
  token: 'USDC',
  chain: 'base',
  rpcUrl: process.env.BASE_RPC_URL!,
  publishedReserves: '36241612000',
  agentId: 'treasury-agent',
});

// The snapshot is now part of your tamper-evident digest chain
const chain = kontext.exportDigestChain();
console.log('Digest chain length:', chain.links.length);`;

const screeningProvidersCode = `import {
  ScreeningAggregator,
  OFACAddressProvider,
  OFACEntityProvider,
  UKOFSIProvider,
  TRMLabsProvider,
} from 'kontext-sdk';

const aggregator = new ScreeningAggregator({
  providers: [
    new OFACAddressProvider(),          // built-in, no API key
    new OFACEntityProvider(),           // built-in, no API key
    new UKOFSIProvider(),               // built-in, no API key
    new TRMLabsProvider({               // requires API key
      apiKey: process.env.TRM_API_KEY!,
    }),
  ],
  consensus: 'ANY_MATCH',              // flag if ANY provider matches
  blocklist: ['0xbad...'],             // always flag these
  allowlist: ['0xsafe...'],            // never flag these
});

const result = await aggregator.screen('0xSuspectAddress');
// result.hit        → true/false (per consensus strategy)
// result.hitCount   → number of providers that matched
// result.matches    → detailed match info per provider
// result.errors     → any provider errors (non-fatal)`;

const paymentComplianceCode = `import { PaymentCompliance, CardCompliance } from 'kontext-sdk';

// General payment compliance (wire, ACH, any fiat flow)
const check = PaymentCompliance.checkPayment({
  amount: '15000',
  currency: 'USD',
  from: 'Acme Corporation',
  to: 'Global Payments Inc',
  agentId: 'ap-system',
  paymentMethod: 'wire',
});
// check.compliant → true/false
// check.checks    → OFAC entity screening + BSA thresholds

// Card payment compliance (agent virtual cards)
const cardCheck = CardCompliance.checkCardPayment({
  amount: '2500',
  currency: 'USD',
  from: 'agent-card-v1',
  to: 'merchant-name',
  agentId: 'purchasing-agent',
  mcc: '5411',              // Grocery Stores
  merchantCountry: 'US',
});
// cardCheck includes MCC risk classification + country screening`;

const walletMonitorCode = `import { Kontext, WalletMonitor } from 'kontext-sdk';

const kontext = Kontext.init({ projectId: 'my-app' });

const monitor = new WalletMonitor(kontext, {
  addresses: [
    { address: '0xMyWallet...', chain: 'base' },
  ],
  rpcUrls: { base: process.env.BASE_RPC_URL! },
  pollingIntervalMs: 4000,
}, { agentId: 'wallet-watcher', tokens: ['USDC', 'USDT'] });

await monitor.start();
// Now watching for all outgoing stablecoin transfers
// Each transfer auto-runs verify() and logs to digest chain`;

const cliMcpCode = `# Start the MCP server
kontext mcp

# Add to Claude Code / Cursor / Windsurf config:
{
  "mcpServers": {
    "kontext": {
      "command": "npx",
      "args": ["@kontext-sdk/cli", "mcp"]
    }
  }
}

# 8 MCP tools exposed:
# - kontext_check: static compliance check
# - kontext_verify: full verification
# - kontext_reason: log agent reasoning
# - kontext_cert: generate certificate
# - kontext_audit: export audit trail
# - kontext_trust: get trust score
# - kontext_anchor: on-chain anchoring
# - kontext_attest: A2A attestation`;

const sidebarSections = [
  {
    title: "Getting Started",
    items: [
      { id: "installation", label: "Installation" },
      { id: "quickstart", label: "Quick Start" },
      { id: "auto-instrumentation", label: "Auto-Instrumentation" },
    ],
  },
  {
    title: "Core Features",
    items: [
      { id: "action-logging", label: "Action Logging" },
      { id: "task-confirmation", label: "Task Confirmation" },
      { id: "audit-export", label: "Audit Export" },
      { id: "trust-scoring", label: "Trust Scoring" },
      { id: "anomaly-detection", label: "Anomaly Detection" },
      { id: "reserve-reconciliation", label: "Reserve Reconciliation" },
    ],
  },
  {
    title: "On-Chain & A2A",
    items: [
      { id: "on-chain-anchoring", label: "On-Chain Anchoring" },
      { id: "a2a-attestation", label: "A2A Attestation" },
      { id: "agent-provenance", label: "Agent Provenance" },
    ],
  },
  {
    title: "Agent Forensics",
    items: [
      { id: "agent-identity", label: "Agent Identity" },
      { id: "wallet-clustering", label: "Wallet Clustering" },
      { id: "confidence-scoring", label: "Confidence Scoring" },
    ],
  },
  {
    title: "Integrations",
    items: [
      { id: "wallet-providers", label: "Wallet Providers" },
      { id: "screening-providers", label: "Screening Providers" },
      { id: "payment-compliance", label: "Payment Compliance" },
    ],
  },
  {
    title: "Python Client",
    items: [
      { id: "python-install", label: "Installation" },
      { id: "python-usage", label: "Usage" },
    ],
  },
  {
    title: "CLI",
    items: [
      { id: "cli-install", label: "Installation" },
      { id: "cli-commands", label: "Commands" },
      { id: "cli-init", label: "Interactive Setup" },
      { id: "cli-mcp", label: "MCP Server" },
    ],
  },
  {
    title: "Reference",
    items: [
      { id: "api", label: "API Reference" },
      { id: "configuration", label: "Configuration" },
      { id: "types", label: "TypeScript Types" },
    ],
  },
];

export default function DocsPage() {
  return (
    <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      {/* Mobile section nav */}
      <div className="sticky top-16 z-40 -mx-4 overflow-x-auto border-b border-border bg-background px-4 py-3 lg:hidden sm:-mx-6 sm:px-6">
        <div className="flex gap-2 min-w-max">
          {sidebarSections.flatMap((section) =>
            section.items.map((item) => (
              <a
                key={item.id}
                href={`#${item.id}`}
                className="inline-flex shrink-0 border border-border px-3 py-1.5 text-xs text-muted-foreground transition-colors hover:text-foreground hover:bg-[var(--term-surface-2)]"
              >
                {item.label}
              </a>
            ))
          )}
        </div>
      </div>

      <div className="flex flex-col lg:flex-row gap-8 lg:gap-12 py-10">
        {/* Sidebar */}
        <aside className="hidden w-64 shrink-0 lg:block">
          <nav className="sticky top-24 space-y-6">
            {sidebarSections.map((section) => (
              <div key={section.title}>
                <h4 className="text-[10px] font-semibold uppercase tracking-widest text-[var(--term-text-3)]">
                  {section.title}
                </h4>
                <ul className="mt-2 space-y-0.5">
                  {section.items.map((item) => (
                    <li key={item.id}>
                      <a
                        href={`#${item.id}`}
                        className="block border-l-2 border-transparent px-3 py-1.5 text-xs text-[var(--term-text-2)] transition-colors hover:text-[var(--term-text)] hover:border-[var(--term-green)] hover:bg-[var(--term-surface-2)]"
                      >
                        {item.label}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </nav>
        </aside>

        {/* Content */}
        <div className="min-w-0 flex-1">
          <div className="prose-kontext max-w-3xl">
            {/* Header */}
            <div className="mb-12">
              <h1 className="text-sm font-medium">
                <span className="text-[var(--term-green)]">$</span>{" "}
                DOCUMENTATION
              </h1>
              <p>
                Kontext is the trust layer for agentic stablecoin and fiat payments.
                Cryptographic verifiable intent for org-wide payments using one line
                of code and a CLI. Available as a TypeScript SDK (npm), CLI, and
                Python client (PyPI).
              </p>
            </div>

            {/* Quick links */}
            <div className="mb-12 grid gap-4 sm:grid-cols-2">
              {[
                {
                  icon: Zap,
                  title: "Quick Start",
                  description: "One command + one line of code",
                  href: "#quickstart",
                },
                {
                  icon: Shield,
                  title: "Auto-Instrumentation",
                  description: "Automatic verification for every transfer",
                  href: "#auto-instrumentation",
                },
                {
                  icon: Code2,
                  title: "API Reference",
                  description: "Full API documentation",
                  href: "#api",
                },
                {
                  icon: BookOpen,
                  title: "Examples",
                  description: "Real-world code examples",
                  href: "#quickstart",
                },
              ].map((link) => (
                <a
                  key={link.title}
                  href={link.href}
                  className="group flex items-start gap-3 border border-border p-4 no-underline transition-colors hover:bg-card"
                >
                  <div className="mt-0.5  bg-[var(--term-surface-2)] p-2 text-primary">
                    <link.icon size={16} />
                  </div>
                  <div>
                    <div className="text-sm font-semibold text-foreground group-hover:text-primary">
                      {link.title}
                    </div>
                    <div className="text-xs text-muted-foreground">
                      {link.description}
                    </div>
                  </div>
                </a>
              ))}
            </div>

            <Separator className="my-12" />

            {/* Installation */}
            <section id="installation">
              <h2>Installation</h2>
              <p>
                The fastest way to get started is the CLI wizard:
              </p>
              <CodeBlock
                code={`npx kontext init\nnpm install kontext-sdk`}
                language="bash"
                filename="Terminal"
              />
              <p className="mt-4">
                Or with yarn / pnpm:
              </p>
              <CodeBlock
                code={`yarn add kontext-sdk\n# or\npnpm add kontext-sdk`}
                language="bash"
                filename="Terminal"
              />
              <p className="mt-4">
                <strong>Python:</strong>
              </p>
              <CodeBlock
                code={pythonInstallCode}
                language="bash"
                filename="Terminal"
              />
              <p>
                <strong>Requirements:</strong> Node.js 18+ and TypeScript 5.0+
                for the SDK. Python 3.9+ for the Python client.
                The TypeScript SDK has zero runtime dependencies.
              </p>
            </section>

            <Separator className="my-12" />

            {/* Quick Start */}
            <section id="quickstart">
              <h2>Quick Start</h2>
              <p>
                Run one command. Wrap your client. Every stablecoin transfer
                gets cryptographic verifiable intent automatically.
              </p>
              <h3>Step 1: Initialize your project</h3>
              <CodeBlock
                code={`npx kontext init`}
                language="bash"
                filename="Terminal"
              />
              <h3>Step 2: Wrap your client (one line)</h3>
              <CodeBlock
                code={quickStartCode}
                language="typescript"
                filename="agent.ts"
              />
              <p>
                For explicit control over individual transactions, use{" "}
                <code>verify()</code> directly:
              </p>
              <CodeBlock
                code={explicitVerifyCode}
                language="typescript"
                filename="verify.ts"
              />
            </section>

            <Separator className="my-12" />

            {/* Auto-Instrumentation */}
            <section id="auto-instrumentation">
              <h2>Auto-Instrumentation</h2>
              <Badge variant="outline" className="mb-4">v0.10.0</Badge>
              <p>
                Instead of manually calling <code>verify()</code> on every transaction,
                auto-instrumentation logs every stablecoin transfer automatically.
                Two layers work together for full coverage:
              </p>
              <p>
                <strong>Layer 1 — Code wrap:</strong>{" "}
                <code>withKontextCompliance(client, kontext)</code> intercepts{" "}
                <code>sendTransaction</code> and <code>writeContract</code> calls
                on your viem client. Can block non-compliant transfers in pre-send mode.
              </p>
              <p>
                <strong>Layer 2 — Chain listener:</strong> The SDK watches your
                monitored wallet addresses on-chain for ERC-20 Transfer events.
                Catches transfers from any source — other scripts, wallet UIs,
                Circle dashboard, autonomous agents.
              </p>
              <h3>Step 1: Run the CLI wizard</h3>
              <CodeBlock
                code={autoInstrumentationCode}
                language="bash"
                filename="Terminal"
              />
              <h3>Step 2: Wrap your client (2 lines)</h3>
              <CodeBlock
                code={autoInstrumentationCodeTS}
                language="typescript"
                filename="agent.ts"
              />
              <h3>Config file format</h3>
              <p>
                The wizard generates a <code>kontext.config.json</code> that the SDK
                reads automatically via <code>Kontext.init()</code> (zero-arg).
                You can also create or edit this file manually.
              </p>
              <CodeBlock
                code={autoInstrumentationConfigCode}
                language="json"
                filename="kontext.config.json"
              />
              <p>
                Deduplication is built-in — if both the code wrap and chain listener
                catch the same transaction, it is only verified once.
              </p>
            </section>

            <Separator className="my-12" />

            {/* Action Logging */}
            <section id="action-logging">
              <h2>Action Logging</h2>
              <p>
                Every action your agents take should be logged for auditability.
                Kontext provides action logging, transaction logging, and
                reasoning logging -- each feeds into the digest chain.
              </p>
              <CodeBlock
                code={actionLoggingCode}
                language="typescript"
                filename="logging.ts"
              />
              <p>
                Reasoning entries are separate from action logs. When regulators
                ask &quot;why did your agent approve that transfer?&quot; -- reasoning
                logs are your answer.
              </p>
            </section>

            <Separator className="my-12" />

            {/* Task Confirmation */}
            <section id="task-confirmation">
              <h2>Task Confirmation</h2>
              <p>
                For high-value or sensitive actions, create a task that requires
                human approval before the agent proceeds. Tasks track required
                evidence and who confirmed them.
              </p>
              <CodeBlock
                code={taskConfirmationCode}
                language="typescript"
                filename="confirmation.ts"
              />
            </section>

            <Separator className="my-12" />

            {/* Audit Export */}
            <section id="audit-export">
              <h2>Audit Export</h2>
              <p>
                Export your complete audit trail as JSON (CSV on Pro). The
                digest chain provides cryptographic proof that no records have
                been tampered with. Generate compliance certificates that bundle
                the audit trail, trust scores, and reasoning.
              </p>
              <CodeBlock
                code={auditExportCode}
                language="typescript"
                filename="export.ts"
              />
            </section>

            <Separator className="my-12" />

            {/* Trust Scoring */}
            <section id="trust-scoring">
              <h2>Trust Scoring</h2>
              <p>
                Every agent gets a trust score from 0 to 100, computed from five
                factors: history, amount patterns, transaction frequency,
                destination trust, and behavioral consistency. Use it to
                gate actions, set thresholds, or flag agents for review.
              </p>
              <CodeBlock
                code={trustScoringCode}
                language="typescript"
                filename="trust.ts"
              />
            </section>

            <Separator className="my-12" />

            {/* Anomaly Detection */}
            <section id="anomaly-detection">
              <h2>Anomaly Detection</h2>
              <p>
                Enable rule-based anomaly detection to flag or block suspicious
                agent behavior. The free tier includes two rules (<code>unusualAmount</code> and <code>frequencySpike</code>).
                Pro unlocks four more: <code>newDestination</code>, <code>offHoursActivity</code>, <code>rapidSuccession</code>,
                and <code>roundAmount</code>.
              </p>
              <CodeBlock
                code={anomalyDetectionCode}
                language="typescript"
                filename="anomaly.ts"
              />
            </section>

            <Separator className="my-12" />

            {/* Reserve Reconciliation */}
            <section id="reserve-reconciliation">
              <h2>Reserve Reconciliation</h2>
              <p>
                Query on-chain <code>totalSupply()</code> for USDC, USDT, DAI, and EURC.
                Compare against published reserve figures from the issuer. Get reconciliation
                status with block-level proof — all from one SDK call. Read-only, zero
                dependencies, uses native <code>fetch()</code> with JSON-RPC.
              </p>
              <CodeBlock
                code={reserveReconciliationCode}
                language="typescript"
                filename="reserve.ts"
              />
              <h3 className="mt-8 text-lg font-semibold">With Digest Chain Logging</h3>
              <p>
                Use the Kontext client method to automatically log each reserve snapshot
                into your tamper-evident digest chain:
              </p>
              <CodeBlock
                code={reserveReconciliationClientCode}
                language="typescript"
                filename="reserve-logged.ts"
              />
              <h3 className="mt-8 text-lg font-semibold">Reconciliation Status</h3>
              <div className="mt-4 overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-[var(--term-surface-2)]">
                      <th className="text-left py-2 pr-4 text-[var(--term-text-2)]">Status</th>
                      <th className="text-left py-2 text-[var(--term-text-2)]">Meaning</th>
                    </tr>
                  </thead>
                  <tbody className="text-[var(--term-text-3)]">
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>matched</code></td><td>On-chain supply exactly matches published reserves</td></tr>
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>delta_within_tolerance</code></td><td>Delta exists but within the configured tolerance (default 0.1%)</td></tr>
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>discrepancy</code></td><td>Delta exceeds tolerance — investigate</td></tr>
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>unverified</code></td><td>No published reserves supplied — supply-only snapshot</td></tr>
                  </tbody>
                </table>
              </div>
              <p className="mt-4">
                Supported tokens: USDC, USDT, DAI, EURC across all 8 chains.
                Use <code>ReserveReconciler.getSupportedChains(token)</code> to list
                available chains for a token, and <code>ReserveReconciler.getContractAddress(token, chain)</code> to
                look up the contract address.
              </p>
            </section>

            <Separator className="my-12" />

            {/* On-Chain Anchoring */}
            <section id="on-chain-anchoring">
              <h2>On-Chain Anchoring</h2>
              <p>
                The digest chain gives you tamper-evidence at the software level.
                On-chain anchoring takes it further -- write the terminal digest
                to a smart contract on Base or Arc. Now anyone can independently verify
                that your compliance checks ran at a specific block height. No
                Kontext account needed.
              </p>
              <CodeBlock
                code={onChainAnchoringCode}
                language="typescript"
                filename="anchoring.ts"
              />
              <p>
                The <code>verifyAnchor()</code> and <code>getAnchor()</code> functions
                have zero dependencies -- they use native <code>fetch()</code> with
                ABI-encoded RPC calls. The <code>anchorDigest()</code> write function
                requires <code>viem</code> as a peer dependency.
              </p>
              <h3 className="mt-6">Deployed contracts</h3>
              <ul className="list-disc pl-6 space-y-1">
                <li>
                  <strong>Base mainnet (verified):</strong>{" "}
                  <a
                    href="https://basescan.org/address/0x89725bc547c5e38f0c2a56758723514acf411a86#code"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="underline font-mono text-sm"
                  >
                    0x89725bc547c5e38f0c2a56758723514acf411a86
                  </a>
                </li>
                <li>
                  <strong>Base Sepolia (testnet):</strong>{" "}
                  <a
                    href="https://sepolia.basescan.org/address/0xbc711590bca89bf944cdfb811129f74d8fb75b46"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="underline font-mono text-sm"
                  >
                    0xbc711590bca89bf944cdfb811129f74d8fb75b46
                  </a>
                </li>
              </ul>
            </section>

            <Separator className="my-12" />

            {/* A2A Attestation */}
            <section id="a2a-attestation">
              <h2>A2A Attestation</h2>
              <p>
                When two agents transact, both sides need proof that the other
                ran compliance. A2A attestation handles this automatically --
                pass a <code>counterparty</code> config to <code>verify()</code> and
                the SDK exchanges digests via the counterparty&apos;s <code>/.well-known/kontext.json</code> agent
                card and <code>/kontext/attest</code> endpoint.
              </p>
              <CodeBlock
                code={a2aAttestationCode}
                language="typescript"
                filename="attestation.ts"
              />
              <p>
                The attestation protocol uses native <code>fetch()</code> with zero
                dependencies. Both agents end up with the other&apos;s digest linked
                in their audit trail -- bilateral, cryptographic proof of mutual
                compliance.
              </p>
            </section>

            <Separator className="my-12" />

            {/* Agent Provenance */}
            <section id="agent-provenance">
              <h2>Agent Provenance</h2>
              <p>
                Agent provenance adds three layers of accountability on top of the
                digest chain. Each layer answers a different question regulators ask.
              </p>
              <h3>Layer 1: Session Delegation</h3>
              <p>
                Records who authorized the agent to act. Every session captures the
                delegator, the agent, the permitted scope, and an optional expiration.
                The agent cannot create its own session -- a human or upstream system
                delegates authority.
              </p>
              <h3>Layer 2: Action Binding</h3>
              <p>
                Every <code>verify()</code>, <code>log()</code>, and <code>logReasoning()</code> call
                accepts a <code>sessionId</code>. The action envelope binds the call to the
                session that authorized it. Actions without a <code>sessionId</code> still log
                normally but lack the provenance binding.
              </p>
              <h3>Layer 3: Human Attestation</h3>
              <p>
                After actions execute, a human reviewer creates a checkpoint that
                references specific action IDs, then attests to it with a signature.
                The attestation key is held by the reviewer -- the agent never touches it.
                This proves a human reviewed the actions, not just that they ran.
              </p>
              <CodeBlock
                code={agentProvenanceCode}
                language="typescript"
                filename="provenance.ts"
              />
              <h3>CLI Commands</h3>
              <CodeBlock
                code={`# Create a session for an agent
npx kontext-sdk session create --agent treasury-agent --delegated-by user:vinay --scope transfer,approve

# List active sessions
npx kontext-sdk session list --agent treasury-agent

# End a session
npx kontext-sdk session end <sessionId>

# Create a checkpoint referencing specific actions
npx kontext-sdk checkpoint create --session <sessionId> --actions act_1,act_2 --summary "Reviewed transfers"

# Attest a checkpoint (human signs off)
npx kontext-sdk checkpoint attest <checkpointId> --attested-by compliance@company.com

# List checkpoints for a session
npx kontext-sdk checkpoint list --session <sessionId>`}
                language="bash"
                filename="Terminal"
              />
            </section>

            <Separator className="my-12" />

            {/* Agent Identity */}
            <section id="agent-identity">
              <h2>Agent Identity</h2>
              <Badge variant="outline" className="mb-4">Pro</Badge>
              <p>
                Register agent identities with wallet mappings, reverse-lookup
                which agent owns a wallet, and manage identity lifecycles.
                Requires the Pro plan (<code>kya-identity</code> gate).
              </p>
              <CodeBlock
                code={agentIdentityCode}
                language="typescript"
                filename="agent-identity.ts"
              />
            </section>

            <Separator className="my-12" />

            {/* Wallet Clustering */}
            <section id="wallet-clustering">
              <h2>Wallet Clustering</h2>
              <Badge variant="outline" className="mb-4">Pro</Badge>
              <p>
                Detect wallets controlled by the same agent using a Union-Find
                algorithm with 5 heuristics. Each cluster includes evidence
                trails documenting why wallets were grouped.
              </p>
              <CodeBlock
                code={walletClusteringCode}
                language="typescript"
                filename="wallet-clustering.ts"
              />
            </section>

            <Separator className="my-12" />

            {/* Confidence Scoring */}
            <section id="confidence-scoring">
              <h2>Confidence Scoring</h2>
              <Badge variant="outline" className="mb-4">Pro</Badge>
              <p>
                Compute a composite identity confidence score (0-100) for
                registered agents. The score combines 5 components:
                identity-completeness, wallet-verification, behavioral-consistency,
                historical-depth, and cluster-coherence.
              </p>
              <CodeBlock
                code={confidenceScoringCode}
                language="typescript"
                filename="confidence-scoring.ts"
              />
            </section>

            <Separator className="my-12" />

            {/* Wallet Providers */}
            <section id="wallet-providers">
              <h2>Wallet Providers</h2>
              <Badge variant="outline" className="mb-4">Enterprise</Badge>
              <p>
                Configure Kontext to work with your preferred wallet provider for
                compliance-wrapped wallet operations. The <code>kontext init</code> wizard
                sets up credentials, validates API access, and stores secrets securely.
                All <code>transferWithCompliance()</code> methods automatically run
                {" "}<code>verify()</code> before executing transfers.
              </p>

              <h3 className="mt-8 text-lg font-semibold">Configuration</h3>
              <p className="text-muted-foreground mb-4">
                Run <code>npx @kontext-sdk/cli init</code> and select your wallet provider.
                The wizard generates a <code>kontext.config.json</code> with your provider config:
              </p>
              <CodeBlock
                code={walletProviderConfigCode}
                language="json"
                filename="kontext.config.json"
              />

              <h3 className="mt-8 text-lg font-semibold">Circle Programmable Wallets</h3>
              <p className="text-muted-foreground mb-4">
                Developer-controlled wallets via Circle&apos;s W3S API. Create wallet sets,
                manage wallets, and execute transfers with automatic OFAC screening and
                audit trail logging.
              </p>
              <CodeBlock
                code={walletProviderCircleCode}
                language="typescript"
                filename="circle-wallets.ts"
              />

              <h3 className="mt-8 text-lg font-semibold">Coinbase Developer Platform (CDP)</h3>
              <p className="text-muted-foreground mb-4">
                Server-side wallets via Coinbase CDP. Ed25519 JWT authentication with
                separate wallet auth for transaction signing.
              </p>
              <CodeBlock
                code={walletProviderCoinbaseCode}
                language="typescript"
                filename="coinbase-wallets.ts"
              />

              <h3 className="mt-8 text-lg font-semibold">MetaMask Embedded Wallets</h3>
              <p className="text-muted-foreground mb-4">
                Embedded wallets via Web3Auth Node SDK. Stateless and sessionless — each
                connection is independent. Requires <code>@web3auth/node-sdk</code> as
                a peer dependency. Infura RPC access is pre-integrated.
              </p>
              <CodeBlock
                code={walletProviderMetaMaskCode}
                language="typescript"
                filename="metamask-wallets.ts"
              />
            </section>

            <Separator className="my-12" />

            {/* Screening Providers */}
            <section id="screening-providers">
              <h2>Screening Providers</h2>
              <p>
                The <code>ScreeningAggregator</code> orchestrates multiple sanctions screening
                providers with configurable consensus strategies. Route queries to compatible
                providers, apply blocklist/allowlist overrides, and get aggregated results
                with per-provider detail.
              </p>
              <CodeBlock
                code={screeningProvidersCode}
                language="typescript"
                filename="screening.ts"
              />
              <h3 className="mt-8 text-lg font-semibold">Available Providers</h3>
              <div className="mt-4 overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-[var(--term-surface-2)]">
                      <th className="text-left py-2 pr-4 text-[var(--term-text-2)]">Provider</th>
                      <th className="text-left py-2 pr-4 text-[var(--term-text-2)]">Lists</th>
                      <th className="text-left py-2 text-[var(--term-text-2)]">API Key</th>
                    </tr>
                  </thead>
                  <tbody className="text-[var(--term-text-3)]">
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>OFACAddressProvider</code></td><td className="pr-4">OFAC SDN (addresses)</td><td>No — built-in</td></tr>
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>OFACEntityProvider</code></td><td className="pr-4">OFAC SDN (entity names)</td><td>No — built-in</td></tr>
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>UKOFSIProvider</code></td><td className="pr-4">UK OFSI sanctions</td><td>No — built-in</td></tr>
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>OpenSanctionsLocalProvider</code></td><td className="pr-4">OpenSanctions (local)</td><td>No — synced via CLI</td></tr>
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>OpenSanctionsProvider</code></td><td className="pr-4">OpenSanctions (API)</td><td>Yes</td></tr>
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>ChainalysisOracleProvider</code></td><td className="pr-4">Chainalysis on-chain oracle</td><td>Yes</td></tr>
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>ChainalysisFreeAPIProvider</code></td><td className="pr-4">Chainalysis free API</td><td>Yes</td></tr>
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>TRMLabsProvider</code></td><td className="pr-4">TRM Labs screening</td><td>Yes</td></tr>
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>KontextCloudScreeningProvider</code></td><td className="pr-4">Kontext Cloud (hosted)</td><td>Yes — Kontext API key</td></tr>
                  </tbody>
                </table>
              </div>
              <h3 className="mt-8 text-lg font-semibold">Consensus Strategies</h3>
              <ul className="list-disc pl-6 space-y-1 mt-2">
                <li><code>ANY_MATCH</code> — flag if any provider reports a hit (most conservative)</li>
                <li><code>MAJORITY</code> — flag if more than half of providers report a hit</li>
                <li><code>ALL_MATCH</code> — flag only if all providers agree (fewest false positives)</li>
              </ul>
            </section>

            <Separator className="my-12" />

            {/* Payment Compliance */}
            <section id="payment-compliance">
              <h2>Payment Compliance</h2>
              <p>
                Compliance checks for non-crypto payment rails: wire transfers, ACH, card
                payments. Performs name-based OFAC entity screening and BSA threshold checks
                ($3K Travel Rule, $10K CTR, $50K large transaction). Returns the same
                check format as <code>UsdcCompliance</code> for consistency across all rails.
              </p>
              <CodeBlock
                code={paymentComplianceCode}
                language="typescript"
                filename="payment-compliance.ts"
              />
              <h3 className="mt-8 text-lg font-semibold">Wallet Monitor</h3>
              <p>
                Watch monitored wallet addresses on-chain for stablecoin Transfer events.
                Catches all outgoing transfers regardless of origin and auto-runs{" "}
                <code>verify()</code> on each one. Uses viem&#39;s <code>watchEvent</code> with
                HTTP polling — works with any RPC endpoint.
              </p>
              <CodeBlock
                code={walletMonitorCode}
                language="typescript"
                filename="wallet-monitor.ts"
              />
            </section>

            <Separator className="my-12" />

            {/* Python Client Installation */}
            <section id="python-install">
              <h2>Python Client</h2>
              <p>
                The Python client (<code>kontext-sdk</code> on PyPI) provides typed
                sync and async HTTP bindings for the Kontext REST API. All compliance
                logic runs server-side — the Python package is a thin wrapper with
                zero local processing.
              </p>
              <CodeBlock
                code={pythonInstallCode}
                language="bash"
                filename="Terminal"
              />
              <p>
                <strong>Requirements:</strong> Python 3.9+. Dependencies: <code>httpx</code> and <code>pydantic</code>.
              </p>
            </section>

            <Separator className="my-12" />

            {/* Python Client Usage */}
            <section id="python-usage">
              <h2>Python Usage</h2>
              <h3>Sync Client</h3>
              <CodeBlock
                code={pythonQuickStartCode}
                language="python"
                filename="agent.py"
              />
              <h3>Async Client</h3>
              <CodeBlock
                code={pythonAsyncCode}
                language="python"
                filename="async_agent.py"
              />
              <h3>API Methods</h3>
              <div className="mt-4 overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-[var(--term-surface-2)]">
                      <th className="text-left py-2 pr-4 text-[var(--term-text-2)]">Method</th>
                      <th className="text-left py-2 text-[var(--term-text-2)]">Description</th>
                    </tr>
                  </thead>
                  <tbody className="text-[var(--term-text-3)]">
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>log(action, agent_id)</code></td><td>Buffer an action log</td></tr>
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>log_transaction(tx_hash, chain, ...)</code></td><td>Buffer a transaction log</td></tr>
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>flush()</code></td><td>Send buffered actions to server</td></tr>
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>create_task(description, agent_id)</code></td><td>Create human-in-the-loop task</td></tr>
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>get_trust_score(agent_id)</code></td><td>Get agent trust score (0-100)</td></tr>
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>export_audit(format)</code></td><td>Export audit trail (JSON/CSV)</td></tr>
                    <tr className="border-b border-[var(--term-surface-2)]"><td className="py-1.5 pr-4"><code>evaluate_anomalies(amount, agent_id)</code></td><td>Evaluate for anomalies</td></tr>
                    <tr><td className="py-1.5 pr-4"><code>health()</code></td><td>Check API health</td></tr>
                  </tbody>
                </table>
              </div>
            </section>

            <Separator className="my-12" />

            {/* CLI Installation */}
            <section id="cli-install">
              <h2>CLI Installation</h2>
              <p>
                The Kontext CLI (<code>@kontext-sdk/cli</code>) provides 12
                commands for compliance operations from the terminal. Install
                globally or run via npx — no project setup required.
              </p>
              <CodeBlock
                code={cliInstallCode}
                language="bash"
                filename="Terminal"
              />
            </section>

            <Separator className="my-12" />

            {/* CLI Commands */}
            <section id="cli-commands">
              <h2>CLI Commands</h2>
              <p>
                Every SDK operation has a CLI equivalent. Run compliance checks,
                verify transactions, generate certificates, export audit trails,
                and anchor digests — all from the command line.
              </p>
              <CodeBlock
                code={cliCommandsCode}
                language="bash"
                filename="Terminal"
              />
            </section>

            <Separator className="my-12" />

            {/* CLI Interactive Setup */}
            <section id="cli-init">
              <h2>Interactive Setup</h2>
              <p>
                The <code>kontext init</code> wizard requires an interactive terminal.
                It walks you through project configuration, wallet provider credentials,
                API key scope guidance, credential validation, and secret storage —
                decisions that involve security settings requiring human review.
              </p>
              <h3>What the wizard configures</h3>
              <ul className="list-disc pl-6 space-y-1">
                <li>Project name and agent ID</li>
                <li>Chain selection (Base, Ethereum, Polygon, Arbitrum, Optimism, Avalanche)</li>
                <li>Token selection (USDC, USDT, DAI, EURC)</li>
                <li>Compliance mode (post-send, pre-send, both)</li>
                <li>Wallet provider (Circle, Coinbase CDP, MetaMask) with credential guidance</li>
                <li>Secret storage (.env, GCP Secret Manager, AWS Secrets Manager, Vault)</li>
              </ul>
              <h3 className="mt-6">Config template</h3>
              <p>
                To preview the config schema without running the wizard, use{" "}
                <code>--json</code>. This prints a starter template to stdout
                without writing to disk:
              </p>
              <CodeBlock
                code={`kontext init --json`}
                language="bash"
                filename="Terminal"
              />
              <h3 className="mt-6">For AI agents</h3>
              <p>
                Agents interacting with Kontext use the{" "}
                <a href="#cli-mcp" className="underline">MCP server</a> (<code>kontext mcp</code>),
                which exposes compliance tools (verify, check, reason, cert, audit,
                trust, anchor). The MCP server assumes <code>kontext init</code> has
                already been run by a human in an interactive terminal. If an agent
                detects that initialization is needed, it should instruct the developer
                to run <code>kontext init</code> in their terminal.
              </p>
            </section>

            <Separator className="my-12" />

            {/* CLI MCP Server */}
            <section id="cli-mcp">
              <h2>MCP Server</h2>
              <p>
                The CLI includes a built-in MCP (Model Context Protocol) server
                that exposes 8 compliance tools to AI coding assistants like
                Claude Code, Cursor, and Windsurf. Start it
                with <code>kontext mcp</code>.
              </p>
              <CodeBlock
                code={cliMcpCode}
                language="bash"
                filename="Terminal"
              />
            </section>

            <Separator className="my-12" />

            {/* API Reference */}
            <section id="api">
              <h2>API Reference</h2>
              <p>
                Complete reference for all Kontext SDK methods. The SDK uses a
                private constructor with a static <code>Kontext.init(config)</code> factory.
              </p>
              <CodeBlock
                code={apiReferenceCode}
                language="typescript"
                filename="api-reference.ts"
              />
            </section>

            <Separator className="my-12" />

            {/* Configuration */}
            <section id="configuration">
              <h2>Configuration</h2>
              <p>
                Kontext can be configured in two ways: explicitly via{" "}
                <code>Kontext.init(config)</code>, or automatically via{" "}
                <code>kontext.config.json</code> (generated by <code>npx kontext init</code>).
                When called with no arguments, <code>Kontext.init()</code> searches
                for a config file walking up from the current directory.
              </p>
              <CodeBlock
                code={configCode}
                language="typescript"
                filename="config.ts"
              />

              <h3>Environment Variables</h3>
              <CodeBlock
                code={`KONTEXT_API_KEY=sk_live_...     # API key for cloud mode (Pro)
KONTEXT_CHAIN=base              # Default chain
KONTEXT_ENVIRONMENT=production  # Environment`}
                language="bash"
                filename=".env"
              />
            </section>

            <Separator className="my-12" />

            {/* Types */}
            <section id="types">
              <h2>TypeScript Types</h2>
              <p>
                All types are exported from the main package. Full autocomplete
                in any TypeScript-aware editor.
              </p>
              <CodeBlock
                code={typesCode}
                language="typescript"
                filename="types.ts"
              />
            </section>

            {/* Next steps */}
            <div className="mt-16 border border-border bg-[var(--term-surface)] p-8">
              <h3 className="text-lg font-semibold">Need help?</h3>
              <p className="mt-2 text-muted-foreground">
                If you run into issues or have questions, reach out through any
                of these channels:
              </p>
              <ul className="mt-4">
                <li>
                  <a
                    href="https://github.com/Legaci-Labs/kontext"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    GitHub Issues & Discussions
                  </a>
                </li>
                <li>
                  <a href="mailto:hello@kontext.dev">hello@kontext.dev</a>
                </li>
                <li>
                  <a
                    href="https://x.com/kontextverify"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    @kontextverify on X
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
