// ============================================================================
// Dashboard Mock Data — drop-in replacements for dashboard-api.ts functions
// ============================================================================

import type {
  KpiData,
  VerificationEvent,
  EvidenceBundle,
  AgentData,
  PolicyData,
  PolicyViolation,
  EventsFilters,
} from './dashboard-api';

// ---- helpers ----------------------------------------------------------------

function ago(minutes: number): string {
  return new Date(Date.now() - minutes * 60_000).toISOString();
}

let _eventCounter = 0;
function nextId(): string {
  _eventCounter++;
  return `evt_mock_${String(_eventCounter).padStart(3, '0')}`;
}

// ---- static mock data -------------------------------------------------------

const MOCK_EVENTS: VerificationEvent[] = [
  {
    event_id: 'evt_a1b2c3d4',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'verified',
    created_at: ago(2),
    workflow: 'stablecoin-payment',
    agent_id: 'payment-agent-v1',
    agent_type: 'payment',
    actor_type: 'autonomous-agent',
    payment_tx_hash: '0x4f2a8c71d4e2b6f8a1c3d5e9f2b4a6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8',
    payment_chain: 'base',
    payment_rail: 'stablecoin',
    payment_token: 'USDC',
    payment_amount: '5200.00',
    payment_currency: 'USD',
    payment_usd_equivalent: '5200.00',
    payment_from_address: '0xd8da6bf26964af9d7eed9e03e53415d37aa96045',
    payment_to_address: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
    payment_destination_country: null,
    policy_decision: 'allow',
    policy_violations: [],
    policy_warnings: [],
    applied_policy_ids: ['pol_amount_limit', 'pol_ofac_screen'],
    ofac_status: 'clear',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 94,
    trust_band: 'high',
    trust_reasons: ['established_agent', 'consistent_behavior', 'no_anomalies'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_a1b2c3d4',
    team_tag: null,
    business_unit_tag: null,
    instrument_id: null,
    instrument_type: null,
    instrument_network: null,
    instrument_issuer: null,
    instrument_scope: null,
    payment_card_last4: null,
    payment_merchant_category_code: null,
    payment_merchant_name: null,
    payment_merchant_country: null,
    payment_three_d_secure: null,
    payment_card_authorization_id: null,
  },
  {
    event_id: 'evt_b2c3d4e5',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'verified',
    created_at: ago(8),
    workflow: 'stablecoin-payment',
    agent_id: 'treasury-agent',
    agent_type: 'treasury',
    actor_type: 'autonomous-agent',
    payment_tx_hash: '0x8c1d3f5a7c9e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0a2c4e6b8d0f2a4c6e8b0',
    payment_chain: 'ethereum',
    payment_rail: 'stablecoin',
    payment_token: 'USDC',
    payment_amount: '12500.00',
    payment_currency: 'USD',
    payment_usd_equivalent: '12500.00',
    payment_from_address: '0xab5801a7d398351b8be11c439e05c5b3259aec9b',
    payment_to_address: '0x47ac0fb4f2d84898e4d9e7b4dab3c24507a6d503',
    payment_destination_country: 'US',
    policy_decision: 'allow',
    policy_violations: [],
    policy_warnings: [],
    applied_policy_ids: ['pol_amount_limit', 'pol_ofac_screen', 'pol_travel_rule'],
    ofac_status: 'clear',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 88,
    trust_band: 'high',
    trust_reasons: ['established_agent', 'allowlisted_destination'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_b2c3d4e5',
    team_tag: 'finance',
    business_unit_tag: null,
    instrument_id: null,
    instrument_type: null,
    instrument_network: null,
    instrument_issuer: null,
    instrument_scope: null,
    payment_card_last4: null,
    payment_merchant_category_code: null,
    payment_merchant_name: null,
    payment_merchant_country: null,
    payment_three_d_secure: null,
    payment_card_authorization_id: null,
  },
  {
    event_id: 'evt_c3d4e5f6',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'verified',
    created_at: ago(15),
    workflow: 'card-payment',
    agent_id: 'payment-agent-v1',
    agent_type: 'payment',
    actor_type: 'autonomous-agent',
    payment_tx_hash: null,
    payment_chain: 'fiat',
    payment_rail: 'card',
    payment_token: 'USD',
    payment_amount: '340.00',
    payment_currency: 'USD',
    payment_usd_equivalent: '340.00',
    payment_from_address: '',
    payment_to_address: '',
    payment_destination_country: 'US',
    policy_decision: 'allow',
    policy_violations: [],
    policy_warnings: [],
    applied_policy_ids: ['pol_card_scope', 'pol_ofac_screen'],
    ofac_status: 'clear',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 92,
    trust_band: 'high',
    trust_reasons: ['established_agent', 'known_merchant'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_c3d4e5f6',
    team_tag: null,
    business_unit_tag: 'ops',
    instrument_id: 'inst_vc_8821',
    instrument_type: 'virtual_card',
    instrument_network: 'Visa',
    instrument_issuer: 'Lithic',
    instrument_scope: { categories: ['software', 'cloud'] },
    payment_card_last4: '4291',
    payment_merchant_category_code: '5734',
    payment_merchant_name: 'Amazon Web Services',
    payment_merchant_country: 'US',
    payment_three_d_secure: 'authenticated',
    payment_card_authorization_id: 'auth_4xK9mP2z',
  },
  {
    event_id: 'evt_d4e5f6g7',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'warning',
    created_at: ago(22),
    workflow: 'stablecoin-payment',
    agent_id: 'treasury-agent',
    agent_type: 'treasury',
    actor_type: 'autonomous-agent',
    payment_tx_hash: '0xf0a2c4e6b8d0f2a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0',
    payment_chain: 'ethereum',
    payment_rail: 'stablecoin',
    payment_token: 'USDC',
    payment_amount: '48000.00',
    payment_currency: 'USD',
    payment_usd_equivalent: '48000.00',
    payment_from_address: '0x71c7656ec7ab88b098defb751b7401b5f6d8976f',
    payment_to_address: '0x2faf487a4414fe77e2327f0bf4ae2a264a776ad2',
    payment_destination_country: 'SG',
    policy_decision: 'warn',
    policy_violations: [],
    policy_warnings: ['amount_near_edd_threshold', 'new_destination_country'],
    applied_policy_ids: ['pol_amount_limit', 'pol_ofac_screen', 'pol_travel_rule'],
    ofac_status: 'clear',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 71,
    trust_band: 'high',
    trust_reasons: ['high_amount', 'new_destination'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_d4e5f6g7',
    team_tag: 'finance',
    business_unit_tag: null,
    instrument_id: null,
    instrument_type: null,
    instrument_network: null,
    instrument_issuer: null,
    instrument_scope: null,
    payment_card_last4: null,
    payment_merchant_category_code: null,
    payment_merchant_name: null,
    payment_merchant_country: null,
    payment_three_d_secure: null,
    payment_card_authorization_id: null,
  },
  {
    event_id: 'evt_e5f6g7h8',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'verified',
    created_at: ago(31),
    workflow: 'stablecoin-payment',
    agent_id: 'defi-arb-bot',
    agent_type: 'trading',
    actor_type: 'autonomous-agent',
    payment_tx_hash: '0x2b4d6f8a0c2e4b6d8f0a2c4e6b8d0f2a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4',
    payment_chain: 'polygon',
    payment_rail: 'stablecoin',
    payment_token: 'USDC',
    payment_amount: '890.00',
    payment_currency: 'USD',
    payment_usd_equivalent: '890.00',
    payment_from_address: '0x503828976ceaa4a8c54eed83191c68f4c9c93e69',
    payment_to_address: '0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
    payment_destination_country: null,
    policy_decision: 'allow',
    policy_violations: [],
    policy_warnings: [],
    applied_policy_ids: ['pol_amount_limit', 'pol_ofac_screen'],
    ofac_status: 'clear',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 83,
    trust_band: 'high',
    trust_reasons: ['established_agent', 'consistent_behavior'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_e5f6g7h8',
    team_tag: null,
    business_unit_tag: null,
    instrument_id: null,
    instrument_type: null,
    instrument_network: null,
    instrument_issuer: null,
    instrument_scope: null,
    payment_card_last4: null,
    payment_merchant_category_code: null,
    payment_merchant_name: null,
    payment_merchant_country: null,
    payment_three_d_secure: null,
    payment_card_authorization_id: null,
  },
  {
    event_id: 'evt_f6g7h8i9',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'blocked',
    created_at: ago(44),
    workflow: 'stablecoin-payment',
    agent_id: 'defi-arb-bot',
    agent_type: 'trading',
    actor_type: 'autonomous-agent',
    payment_tx_hash: null,
    payment_chain: 'base',
    payment_rail: 'stablecoin',
    payment_token: 'USDC',
    payment_amount: '95000.00',
    payment_currency: 'USD',
    payment_usd_equivalent: '95000.00',
    payment_from_address: '0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0',
    payment_to_address: '0x98c3d3183c4b8a650614ad179a1a98be0a8d6b8e',
    payment_destination_country: 'KP',
    policy_decision: 'block',
    policy_violations: ['ofac_sanctions_match', 'destination_country_blocked'],
    policy_warnings: [],
    applied_policy_ids: ['pol_ofac_screen', 'pol_country_block'],
    ofac_status: 'flagged',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 12,
    trust_band: 'low',
    trust_reasons: ['ofac_match', 'sanctioned_country'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_f6g7h8i9',
    team_tag: null,
    business_unit_tag: null,
    instrument_id: null,
    instrument_type: null,
    instrument_network: null,
    instrument_issuer: null,
    instrument_scope: null,
    payment_card_last4: null,
    payment_merchant_category_code: null,
    payment_merchant_name: null,
    payment_merchant_country: null,
    payment_three_d_secure: null,
    payment_card_authorization_id: null,
  },
  {
    event_id: 'evt_g7h8i9j0',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'verified',
    created_at: ago(58),
    workflow: 'card-payment',
    agent_id: 'treasury-agent',
    agent_type: 'treasury',
    actor_type: 'autonomous-agent',
    payment_tx_hash: null,
    payment_chain: 'fiat',
    payment_rail: 'card',
    payment_token: 'USD',
    payment_amount: '520.00',
    payment_currency: 'USD',
    payment_usd_equivalent: '520.00',
    payment_from_address: '',
    payment_to_address: '',
    payment_destination_country: 'US',
    policy_decision: 'allow',
    policy_violations: [],
    policy_warnings: [],
    applied_policy_ids: ['pol_card_scope', 'pol_ofac_screen'],
    ofac_status: 'clear',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 96,
    trust_band: 'high',
    trust_reasons: ['established_agent', 'known_merchant', 'within_scope'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_g7h8i9j0',
    team_tag: 'finance',
    business_unit_tag: null,
    instrument_id: 'inst_vc_5531',
    instrument_type: 'virtual_card',
    instrument_network: 'Mastercard',
    instrument_issuer: 'Lithic',
    instrument_scope: { categories: ['saas', 'infrastructure'] },
    payment_card_last4: '8847',
    payment_merchant_category_code: '7372',
    payment_merchant_name: 'Stripe Inc',
    payment_merchant_country: 'US',
    payment_three_d_secure: 'authenticated',
    payment_card_authorization_id: 'auth_9zR3nQ7w',
  },
  {
    event_id: 'evt_h8i9j0k1',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'verified',
    created_at: ago(72),
    workflow: 'stablecoin-payment',
    agent_id: 'payment-agent-v1',
    agent_type: 'payment',
    actor_type: 'autonomous-agent',
    payment_tx_hash: '0xa0c2e4b6d8f0a2c4e6b8d0f2a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0',
    payment_chain: 'base',
    payment_rail: 'stablecoin',
    payment_token: 'EURC',
    payment_amount: '1750.00',
    payment_currency: 'EUR',
    payment_usd_equivalent: '1907.50',
    payment_from_address: '0x1c24b84c87b73889ec0b1e0f2745e82e81a35b3b',
    payment_to_address: '0x9d0d6d2485ec4e55f9c7fe7b65747c5b52c3a83e',
    payment_destination_country: 'DE',
    policy_decision: 'allow',
    policy_violations: [],
    policy_warnings: [],
    applied_policy_ids: ['pol_amount_limit', 'pol_ofac_screen'],
    ofac_status: 'clear',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 91,
    trust_band: 'high',
    trust_reasons: ['established_agent', 'allowlisted_destination'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_h8i9j0k1',
    team_tag: null,
    business_unit_tag: 'europe',
    instrument_id: null,
    instrument_type: null,
    instrument_network: null,
    instrument_issuer: null,
    instrument_scope: null,
    payment_card_last4: null,
    payment_merchant_category_code: null,
    payment_merchant_name: null,
    payment_merchant_country: null,
    payment_three_d_secure: null,
    payment_card_authorization_id: null,
  },
  {
    event_id: 'evt_i9j0k1l2',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'verified',
    created_at: ago(88),
    workflow: 'stablecoin-payment',
    agent_id: 'payment-agent-v1',
    agent_type: 'payment',
    actor_type: 'autonomous-agent',
    payment_tx_hash: '0xd6f8a0c2e4b6d8f0a2c4e6b8d0f2a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6',
    payment_chain: 'base',
    payment_rail: 'stablecoin',
    payment_token: 'USDC',
    payment_amount: '3300.00',
    payment_currency: 'USD',
    payment_usd_equivalent: '3300.00',
    payment_from_address: '0x8ba1f109551bd432803012645ac136ddd64dba72',
    payment_to_address: '0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be',
    payment_destination_country: null,
    policy_decision: 'allow',
    policy_violations: [],
    policy_warnings: [],
    applied_policy_ids: ['pol_amount_limit', 'pol_ofac_screen', 'pol_travel_rule'],
    ofac_status: 'clear',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 89,
    trust_band: 'high',
    trust_reasons: ['established_agent', 'consistent_behavior'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_i9j0k1l2',
    team_tag: null,
    business_unit_tag: null,
    instrument_id: null,
    instrument_type: null,
    instrument_network: null,
    instrument_issuer: null,
    instrument_scope: null,
    payment_card_last4: null,
    payment_merchant_category_code: null,
    payment_merchant_name: null,
    payment_merchant_country: null,
    payment_three_d_secure: null,
    payment_card_authorization_id: null,
  },
  {
    event_id: 'evt_j0k1l2m3',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'warning',
    created_at: ago(105),
    workflow: 'stablecoin-payment',
    agent_id: 'defi-arb-bot',
    agent_type: 'trading',
    actor_type: 'autonomous-agent',
    payment_tx_hash: '0xe8b0d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0a2c4e6b8d0f2a4c6e8',
    payment_chain: 'polygon',
    payment_rail: 'stablecoin',
    payment_token: 'USDC',
    payment_amount: '7800.00',
    payment_currency: 'USD',
    payment_usd_equivalent: '7800.00',
    payment_from_address: '0x742d35cc6634c0532925a3b8d4c9e7f1d2e3f4g5',
    payment_to_address: '0x5a3c1b7e9f2d4g6h8i0j2k4l6m8n0o2p4q6r8s0',
    payment_destination_country: 'BR',
    policy_decision: 'warn',
    policy_violations: [],
    policy_warnings: ['new_destination_country', 'frequency_near_limit'],
    applied_policy_ids: ['pol_amount_limit', 'pol_ofac_screen'],
    ofac_status: 'clear',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 62,
    trust_band: 'medium',
    trust_reasons: ['new_destination', 'frequency_spike'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_j0k1l2m3',
    team_tag: null,
    business_unit_tag: null,
    instrument_id: null,
    instrument_type: null,
    instrument_network: null,
    instrument_issuer: null,
    instrument_scope: null,
    payment_card_last4: null,
    payment_merchant_category_code: null,
    payment_merchant_name: null,
    payment_merchant_country: null,
    payment_three_d_secure: null,
    payment_card_authorization_id: null,
  },
  {
    event_id: 'evt_k1l2m3n4',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'verified',
    created_at: ago(120),
    workflow: 'stablecoin-payment',
    agent_id: 'treasury-agent',
    agent_type: 'treasury',
    actor_type: 'autonomous-agent',
    payment_tx_hash: '0xb4d6f8a0c2e4b6d8f0a2c4e6b8d0f2a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4',
    payment_chain: 'ethereum',
    payment_rail: 'stablecoin',
    payment_token: 'USDC',
    payment_amount: '18000.00',
    payment_currency: 'USD',
    payment_usd_equivalent: '18000.00',
    payment_from_address: '0x98c3d3183c4b8a650614ad179a1a98be0a8d6b8e',
    payment_to_address: '0xab5801a7d398351b8be11c439e05c5b3259aec9b',
    payment_destination_country: 'US',
    policy_decision: 'allow',
    policy_violations: [],
    policy_warnings: [],
    applied_policy_ids: ['pol_amount_limit', 'pol_ofac_screen', 'pol_travel_rule'],
    ofac_status: 'clear',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 95,
    trust_band: 'high',
    trust_reasons: ['established_agent', 'consistent_behavior', 'allowlisted_destination'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_k1l2m3n4',
    team_tag: 'finance',
    business_unit_tag: null,
    instrument_id: null,
    instrument_type: null,
    instrument_network: null,
    instrument_issuer: null,
    instrument_scope: null,
    payment_card_last4: null,
    payment_merchant_category_code: null,
    payment_merchant_name: null,
    payment_merchant_country: null,
    payment_three_d_secure: null,
    payment_card_authorization_id: null,
  },
  {
    event_id: 'evt_l2m3n4o5',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'blocked',
    created_at: ago(145),
    workflow: 'stablecoin-payment',
    agent_id: 'payment-agent-v1',
    agent_type: 'payment',
    actor_type: 'autonomous-agent',
    payment_tx_hash: null,
    payment_chain: 'base',
    payment_rail: 'stablecoin',
    payment_token: 'USDC',
    payment_amount: '150000.00',
    payment_currency: 'USD',
    payment_usd_equivalent: '150000.00',
    payment_from_address: '0x6626593c237f530d15ae9980a95ef938ac15c35',
    payment_to_address: '0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb',
    payment_destination_country: 'RU',
    policy_decision: 'block',
    policy_violations: ['amount_exceeds_daily_limit', 'destination_country_blocked'],
    policy_warnings: [],
    applied_policy_ids: ['pol_amount_limit', 'pol_country_block', 'pol_ofac_screen'],
    ofac_status: 'clear',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 34,
    trust_band: 'low',
    trust_reasons: ['amount_exceeded', 'blocked_country'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_l2m3n4o5',
    team_tag: null,
    business_unit_tag: null,
    instrument_id: null,
    instrument_type: null,
    instrument_network: null,
    instrument_issuer: null,
    instrument_scope: null,
    payment_card_last4: null,
    payment_merchant_category_code: null,
    payment_merchant_name: null,
    payment_merchant_country: null,
    payment_three_d_secure: null,
    payment_card_authorization_id: null,
  },
  {
    event_id: 'evt_m3n4o5p6',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'verified',
    created_at: ago(162),
    workflow: 'card-payment',
    agent_id: 'defi-arb-bot',
    agent_type: 'trading',
    actor_type: 'autonomous-agent',
    payment_tx_hash: null,
    payment_chain: 'fiat',
    payment_rail: 'card',
    payment_token: 'USD',
    payment_amount: '180.00',
    payment_currency: 'USD',
    payment_usd_equivalent: '180.00',
    payment_from_address: '',
    payment_to_address: '',
    payment_destination_country: 'US',
    policy_decision: 'allow',
    policy_violations: [],
    policy_warnings: [],
    applied_policy_ids: ['pol_card_scope', 'pol_ofac_screen'],
    ofac_status: 'clear',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 87,
    trust_band: 'high',
    trust_reasons: ['established_agent', 'known_merchant'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_m3n4o5p6',
    team_tag: null,
    business_unit_tag: null,
    instrument_id: 'inst_vc_3317',
    instrument_type: 'virtual_card',
    instrument_network: 'Visa',
    instrument_issuer: 'Lithic',
    instrument_scope: { categories: ['software', 'productivity'] },
    payment_card_last4: '6614',
    payment_merchant_category_code: '7372',
    payment_merchant_name: 'Notion Labs Inc',
    payment_merchant_country: 'US',
    payment_three_d_secure: 'not_required',
    payment_card_authorization_id: 'auth_2mL8pN4v',
  },
  {
    event_id: 'evt_n4o5p6q7',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'verified',
    created_at: ago(180),
    workflow: 'stablecoin-payment',
    agent_id: 'treasury-agent',
    agent_type: 'treasury',
    actor_type: 'autonomous-agent',
    payment_tx_hash: '0xc6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0a2c4e6b8d0f2a4c6',
    payment_chain: 'ethereum',
    payment_rail: 'stablecoin',
    payment_token: 'EURC',
    payment_amount: '4200.00',
    payment_currency: 'EUR',
    payment_usd_equivalent: '4578.00',
    payment_from_address: '0x2c2d8f0a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4',
    payment_to_address: '0x8e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0a2c4e6',
    payment_destination_country: 'NL',
    policy_decision: 'allow',
    policy_violations: [],
    policy_warnings: [],
    applied_policy_ids: ['pol_amount_limit', 'pol_ofac_screen'],
    ofac_status: 'clear',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 93,
    trust_band: 'high',
    trust_reasons: ['established_agent', 'consistent_behavior'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_n4o5p6q7',
    team_tag: 'finance',
    business_unit_tag: 'europe',
    instrument_id: null,
    instrument_type: null,
    instrument_network: null,
    instrument_issuer: null,
    instrument_scope: null,
    payment_card_last4: null,
    payment_merchant_category_code: null,
    payment_merchant_name: null,
    payment_merchant_country: null,
    payment_three_d_secure: null,
    payment_card_authorization_id: null,
  },
  {
    event_id: 'evt_o5p6q7r8',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'verified',
    created_at: ago(200),
    workflow: 'stablecoin-payment',
    agent_id: 'payment-agent-v1',
    agent_type: 'payment',
    actor_type: 'autonomous-agent',
    payment_tx_hash: '0x4a6c8e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0a2c4e6b8d0f2a4c6e8b0d2f4a6',
    payment_chain: 'base',
    payment_rail: 'stablecoin',
    payment_token: 'USDC',
    payment_amount: '6700.00',
    payment_currency: 'USD',
    payment_usd_equivalent: '6700.00',
    payment_from_address: '0xd8da6bf26964af9d7eed9e03e53415d37aa96045',
    payment_to_address: '0x4b3c2a1d8e7f6g5h4i3j2k1l0m9n8o7p6q5r4s3',
    payment_destination_country: null,
    policy_decision: 'allow',
    policy_violations: [],
    policy_warnings: [],
    applied_policy_ids: ['pol_amount_limit', 'pol_ofac_screen', 'pol_travel_rule'],
    ofac_status: 'clear',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 90,
    trust_band: 'high',
    trust_reasons: ['established_agent', 'consistent_behavior'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_o5p6q7r8',
    team_tag: null,
    business_unit_tag: null,
    instrument_id: null,
    instrument_type: null,
    instrument_network: null,
    instrument_issuer: null,
    instrument_scope: null,
    payment_card_last4: null,
    payment_merchant_category_code: null,
    payment_merchant_name: null,
    payment_merchant_country: null,
    payment_three_d_secure: null,
    payment_card_authorization_id: null,
  },
  {
    event_id: 'evt_p6q7r8s9',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'verified',
    created_at: ago(225),
    workflow: 'card-payment',
    agent_id: 'payment-agent-v1',
    agent_type: 'payment',
    actor_type: 'autonomous-agent',
    payment_tx_hash: null,
    payment_chain: 'fiat',
    payment_rail: 'card',
    payment_token: 'USD',
    payment_amount: '2100.00',
    payment_currency: 'USD',
    payment_usd_equivalent: '2100.00',
    payment_from_address: '',
    payment_to_address: '',
    payment_destination_country: 'US',
    policy_decision: 'allow',
    policy_violations: [],
    policy_warnings: [],
    applied_policy_ids: ['pol_card_scope', 'pol_ofac_screen'],
    ofac_status: 'clear',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 94,
    trust_band: 'high',
    trust_reasons: ['established_agent', 'known_merchant', 'within_scope'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_p6q7r8s9',
    team_tag: null,
    business_unit_tag: null,
    instrument_id: 'inst_vc_7729',
    instrument_type: 'virtual_card',
    instrument_network: 'Visa',
    instrument_issuer: 'Lithic',
    instrument_scope: { categories: ['infrastructure', 'cloud'] },
    payment_card_last4: '3382',
    payment_merchant_category_code: '7372',
    payment_merchant_name: 'Vercel Inc',
    payment_merchant_country: 'US',
    payment_three_d_secure: 'authenticated',
    payment_card_authorization_id: 'auth_7kM5qP9t',
  },
  {
    event_id: 'evt_q7r8s9t0',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'warning',
    created_at: ago(250),
    workflow: 'stablecoin-payment',
    agent_id: 'defi-arb-bot',
    agent_type: 'trading',
    actor_type: 'autonomous-agent',
    payment_tx_hash: '0x6c8e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0a2c4e6b8d0f2a4c6e8b0d2f4a6c8',
    payment_chain: 'base',
    payment_rail: 'stablecoin',
    payment_token: 'USDC',
    payment_amount: '22000.00',
    payment_currency: 'USD',
    payment_usd_equivalent: '22000.00',
    payment_from_address: '0x503828976ceaa4a8c54eed83191c68f4c9c93e69',
    payment_to_address: '0x9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d',
    payment_destination_country: null,
    policy_decision: 'warn',
    policy_violations: [],
    policy_warnings: ['frequency_near_limit', 'round_amount_pattern'],
    applied_policy_ids: ['pol_amount_limit', 'pol_ofac_screen', 'pol_frequency'],
    ofac_status: 'clear',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 58,
    trust_band: 'medium',
    trust_reasons: ['frequency_spike', 'round_amount'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_q7r8s9t0',
    team_tag: null,
    business_unit_tag: null,
    instrument_id: null,
    instrument_type: null,
    instrument_network: null,
    instrument_issuer: null,
    instrument_scope: null,
    payment_card_last4: null,
    payment_merchant_category_code: null,
    payment_merchant_name: null,
    payment_merchant_country: null,
    payment_three_d_secure: null,
    payment_card_authorization_id: null,
  },
  {
    event_id: 'evt_r8s9t0u1',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'verified',
    created_at: ago(270),
    workflow: 'stablecoin-payment',
    agent_id: 'treasury-agent',
    agent_type: 'treasury',
    actor_type: 'autonomous-agent',
    payment_tx_hash: '0x8e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0a2c4e6b8d0f2a4c6e8b0d2f4a6c8e0',
    payment_chain: 'polygon',
    payment_rail: 'stablecoin',
    payment_token: 'USDC',
    payment_amount: '9400.00',
    payment_currency: 'USD',
    payment_usd_equivalent: '9400.00',
    payment_from_address: '0x47ac0fb4f2d84898e4d9e7b4dab3c24507a6d503',
    payment_to_address: '0xd8da6bf26964af9d7eed9e03e53415d37aa96045',
    payment_destination_country: 'US',
    policy_decision: 'allow',
    policy_violations: [],
    policy_warnings: [],
    applied_policy_ids: ['pol_amount_limit', 'pol_ofac_screen'],
    ofac_status: 'clear',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 97,
    trust_band: 'high',
    trust_reasons: ['established_agent', 'consistent_behavior', 'no_anomalies'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_r8s9t0u1',
    team_tag: 'finance',
    business_unit_tag: null,
    instrument_id: null,
    instrument_type: null,
    instrument_network: null,
    instrument_issuer: null,
    instrument_scope: null,
    payment_card_last4: null,
    payment_merchant_category_code: null,
    payment_merchant_name: null,
    payment_merchant_country: null,
    payment_three_d_secure: null,
    payment_card_authorization_id: null,
  },
  {
    // Reserve snapshot event
    event_id: 'evt_s9t0u1v2',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'verified',
    created_at: ago(295),
    workflow: 'stablecoin-payment',
    agent_id: 'payment-agent-v1',
    agent_type: 'payment',
    actor_type: 'autonomous-agent',
    payment_tx_hash: '0xa2c4e6b8d0f2a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0a2',
    payment_chain: 'base',
    payment_rail: 'stablecoin',
    payment_token: 'USDC',
    payment_amount: '4500.00',
    payment_currency: 'USD',
    payment_usd_equivalent: '4500.00',
    payment_from_address: '0xd8da6bf26964af9d7eed9e03e53415d37aa96045',
    payment_to_address: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
    payment_destination_country: null,
    policy_decision: 'allow',
    policy_violations: [],
    policy_warnings: [],
    applied_policy_ids: ['pol_amount_limit', 'pol_ofac_screen'],
    ofac_status: 'clear',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 94,
    trust_band: 'high',
    trust_reasons: ['established_agent', 'reserve_verified'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_s9t0u1v2',
    team_tag: null,
    business_unit_tag: null,
    instrument_id: null,
    instrument_type: null,
    instrument_network: null,
    instrument_issuer: null,
    instrument_scope: null,
    payment_card_last4: null,
    payment_merchant_category_code: null,
    payment_merchant_name: null,
    payment_merchant_country: null,
    payment_three_d_secure: null,
    payment_card_authorization_id: null,
  },
  {
    event_id: 'evt_t0u1v2w3',
    org_id: 'org_legaci_demo',
    environment: 'production',
    status: 'verified',
    created_at: ago(320),
    workflow: 'stablecoin-payment',
    agent_id: 'defi-arb-bot',
    agent_type: 'trading',
    actor_type: 'autonomous-agent',
    payment_tx_hash: '0xc4e6b8d0f2a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0a2c4',
    payment_chain: 'base',
    payment_rail: 'stablecoin',
    payment_token: 'USDC',
    payment_amount: '2100.00',
    payment_currency: 'USD',
    payment_usd_equivalent: '2100.00',
    payment_from_address: '0x503828976ceaa4a8c54eed83191c68f4c9c93e69',
    payment_to_address: '0x7f2b3a4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a',
    payment_destination_country: null,
    policy_decision: 'allow',
    policy_violations: [],
    policy_warnings: [],
    applied_policy_ids: ['pol_amount_limit', 'pol_ofac_screen'],
    ofac_status: 'clear',
    screening_provider: 'kontext-ofac-v1',
    trust_score: 85,
    trust_band: 'high',
    trust_reasons: ['established_agent', 'consistent_behavior'],
    coverage_status: 'covered',
    evidence_bundle_id: 'evb_t0u1v2w3',
    team_tag: null,
    business_unit_tag: null,
    instrument_id: null,
    instrument_type: null,
    instrument_network: null,
    instrument_issuer: null,
    instrument_scope: null,
    payment_card_last4: null,
    payment_merchant_category_code: null,
    payment_merchant_name: null,
    payment_merchant_country: null,
    payment_three_d_secure: null,
    payment_card_authorization_id: null,
  },
];

// ---- evidence bundles -------------------------------------------------------

const EVIDENCE_MAP: Record<string, EvidenceBundle> = {
  'evb_a1b2c3d4': {
    evidence_bundle_id: 'evb_a1b2c3d4',
    event_id: 'evt_a1b2c3d4',
    org_id: 'org_legaci_demo',
    intent_hash_algorithm: 'sha256',
    intent_hash_value: '7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
    intent_hash_canonical_fields: ['agent_id', 'payment_token', 'payment_amount', 'payment_to_address', 'timestamp'],
    authorization_type: 'policy-scoped-agent',
    authorized: true,
    authorizer: 'kontext-policy-engine-v2',
    authorization_scope: 'stablecoin:base:USDC:5200',
    evaluated_at: ago(2),
    policy_trace: {
      decision: 'allow',
      rules_evaluated: 4,
      passed_rules: ['amount_within_daily_limit', 'ofac_clear', 'destination_allowlisted', 'agent_trusted'],
      failed_rules: [],
      warning_rules: [],
    },
    screening_provider: 'kontext-ofac-v1',
    screening_result: 'clear',
    screened_entity: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
    screening_screened_at: ago(2),
    exec_tx_hash: '0x4f2a8c71d4e2b6f8a1c3d5e9f2b4a6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8',
    exec_chain: 'base',
    exec_observed_onchain: true,
    record_hash: 'a3f8b2c1d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1',
    previous_record_hash: '9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0',
    chain_index: 44281,
    render_headline: 'Verified USDC payout',
    render_subheadline: 'USDC 5,200 via Base · payment-agent-v1',
    render_risk_label: 'low',
    instrument_id: null,
    instrument_issuer: null,
    card_authorization_id: null,
    card_3ds_status: null,
    merchant_screened_name: null,
    scope_evaluation: null,
    created_at: ago(2),
  },
  'evb_b2c3d4e5': {
    evidence_bundle_id: 'evb_b2c3d4e5',
    event_id: 'evt_b2c3d4e5',
    org_id: 'org_legaci_demo',
    intent_hash_algorithm: 'sha256',
    intent_hash_value: '2e7d4c3b8a1f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d',
    intent_hash_canonical_fields: ['agent_id', 'payment_token', 'payment_amount', 'payment_to_address', 'timestamp'],
    authorization_type: 'policy-scoped-agent',
    authorized: true,
    authorizer: 'kontext-policy-engine-v2',
    authorization_scope: 'stablecoin:ethereum:USDC:12500',
    evaluated_at: ago(8),
    policy_trace: {
      decision: 'allow',
      rules_evaluated: 5,
      passed_rules: ['amount_within_daily_limit', 'ofac_clear', 'travel_rule_compliant', 'agent_trusted', 'destination_allowlisted'],
      failed_rules: [],
      warning_rules: [],
    },
    screening_provider: 'kontext-ofac-v1',
    screening_result: 'clear',
    screened_entity: '0x47ac0fb4f2d84898e4d9e7b4dab3c24507a6d503',
    screening_screened_at: ago(8),
    exec_tx_hash: '0x8c1d3f5a7c9e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0a2c4e6b8d0f2a4c6e8b0',
    exec_chain: 'ethereum',
    exec_observed_onchain: true,
    record_hash: 'b4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5',
    previous_record_hash: 'a3f8b2c1d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1',
    chain_index: 44282,
    render_headline: 'Verified USDC treasury transfer',
    render_subheadline: 'USDC 12,500 via Ethereum · treasury-agent',
    render_risk_label: 'low',
    instrument_id: null,
    instrument_issuer: null,
    card_authorization_id: null,
    card_3ds_status: null,
    merchant_screened_name: null,
    scope_evaluation: null,
    created_at: ago(8),
  },
  'evb_c3d4e5f6': {
    evidence_bundle_id: 'evb_c3d4e5f6',
    event_id: 'evt_c3d4e5f6',
    org_id: 'org_legaci_demo',
    intent_hash_algorithm: 'sha256',
    intent_hash_value: '5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d',
    intent_hash_canonical_fields: ['agent_id', 'instrument_id', 'payment_amount', 'merchant_id', 'timestamp'],
    authorization_type: 'virtual-card-scoped',
    authorized: true,
    authorizer: 'kontext-policy-engine-v2',
    authorization_scope: 'card:inst_vc_8821:mcc:5734',
    evaluated_at: ago(15),
    policy_trace: {
      decision: 'allow',
      rules_evaluated: 4,
      passed_rules: ['card_scope_valid', 'ofac_clear', 'mcc_allowlisted', 'amount_within_card_limit'],
      failed_rules: [],
      warning_rules: [],
    },
    screening_provider: 'kontext-ofac-v1',
    screening_result: 'clear',
    screened_entity: 'Amazon Web Services',
    screening_screened_at: ago(15),
    exec_tx_hash: null,
    exec_chain: 'fiat',
    exec_observed_onchain: false,
    record_hash: 'c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6',
    previous_record_hash: 'b4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5',
    chain_index: 44283,
    render_headline: 'Verified card payment — AWS',
    render_subheadline: 'USD 340 via Visa ****4291 · payment-agent-v1',
    render_risk_label: 'low',
    instrument_id: 'inst_vc_8821',
    instrument_issuer: 'Lithic',
    card_authorization_id: 'auth_4xK9mP2z',
    card_3ds_status: 'authenticated',
    merchant_screened_name: 'Amazon Web Services Inc.',
    scope_evaluation: { within_scope: true, violations: [] },
    created_at: ago(15),
  },
  'evb_d4e5f6g7': {
    evidence_bundle_id: 'evb_d4e5f6g7',
    event_id: 'evt_d4e5f6g7',
    org_id: 'org_legaci_demo',
    intent_hash_algorithm: 'sha256',
    intent_hash_value: '6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e',
    intent_hash_canonical_fields: ['agent_id', 'payment_token', 'payment_amount', 'payment_to_address', 'timestamp'],
    authorization_type: 'policy-scoped-agent',
    authorized: true,
    authorizer: 'kontext-policy-engine-v2',
    authorization_scope: 'stablecoin:ethereum:USDC:48000',
    evaluated_at: ago(22),
    policy_trace: {
      decision: 'warn',
      rules_evaluated: 5,
      passed_rules: ['ofac_clear', 'agent_trusted', 'amount_within_daily_limit'],
      failed_rules: [],
      warning_rules: ['amount_near_edd_threshold', 'new_destination_country'],
    },
    screening_provider: 'kontext-ofac-v1',
    screening_result: 'clear',
    screened_entity: '0x2faf487a4414fe77e2327f0bf4ae2a264a776ad2',
    screening_screened_at: ago(22),
    exec_tx_hash: '0xf0a2c4e6b8d0f2a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0',
    exec_chain: 'ethereum',
    exec_observed_onchain: true,
    record_hash: 'd6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7',
    previous_record_hash: 'c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6',
    chain_index: 44284,
    render_headline: 'Warning: Large transfer to new destination',
    render_subheadline: 'USDC 48,000 via Ethereum → SG · treasury-agent',
    render_risk_label: 'medium',
    instrument_id: null,
    instrument_issuer: null,
    card_authorization_id: null,
    card_3ds_status: null,
    merchant_screened_name: null,
    scope_evaluation: null,
    created_at: ago(22),
  },
  'evb_f6g7h8i9': {
    evidence_bundle_id: 'evb_f6g7h8i9',
    event_id: 'evt_f6g7h8i9',
    org_id: 'org_legaci_demo',
    intent_hash_algorithm: 'sha256',
    intent_hash_value: '8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a',
    intent_hash_canonical_fields: ['agent_id', 'payment_token', 'payment_amount', 'payment_to_address', 'timestamp'],
    authorization_type: 'policy-scoped-agent',
    authorized: false,
    authorizer: 'kontext-policy-engine-v2',
    authorization_scope: null,
    evaluated_at: ago(44),
    policy_trace: {
      decision: 'block',
      rules_evaluated: 3,
      passed_rules: [],
      failed_rules: ['ofac_sanctions_match', 'destination_country_blocked'],
      warning_rules: [],
    },
    screening_provider: 'kontext-ofac-v1',
    screening_result: 'flagged',
    screened_entity: '0x98c3d3183c4b8a650614ad179a1a98be0a8d6b8e',
    screening_screened_at: ago(44),
    exec_tx_hash: null,
    exec_chain: 'base',
    exec_observed_onchain: false,
    record_hash: 'e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8',
    previous_record_hash: 'd6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7',
    chain_index: 44285,
    render_headline: 'Blocked: OFAC sanctions match',
    render_subheadline: 'USDC 95,000 blocked · defi-arb-bot',
    render_risk_label: 'critical',
    instrument_id: null,
    instrument_issuer: null,
    card_authorization_id: null,
    card_3ds_status: null,
    merchant_screened_name: null,
    scope_evaluation: null,
    created_at: ago(44),
  },
  'evb_g7h8i9j0': {
    evidence_bundle_id: 'evb_g7h8i9j0',
    event_id: 'evt_g7h8i9j0',
    org_id: 'org_legaci_demo',
    intent_hash_algorithm: 'sha256',
    intent_hash_value: '9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b',
    intent_hash_canonical_fields: ['agent_id', 'instrument_id', 'payment_amount', 'merchant_id', 'timestamp'],
    authorization_type: 'virtual-card-scoped',
    authorized: true,
    authorizer: 'kontext-policy-engine-v2',
    authorization_scope: 'card:inst_vc_5531:mcc:7372',
    evaluated_at: ago(58),
    policy_trace: {
      decision: 'allow',
      rules_evaluated: 4,
      passed_rules: ['card_scope_valid', 'ofac_clear', 'mcc_allowlisted', 'amount_within_card_limit'],
      failed_rules: [],
      warning_rules: [],
    },
    screening_provider: 'kontext-ofac-v1',
    screening_result: 'clear',
    screened_entity: 'Stripe Inc',
    screening_screened_at: ago(58),
    exec_tx_hash: null,
    exec_chain: 'fiat',
    exec_observed_onchain: false,
    record_hash: 'f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9',
    previous_record_hash: 'e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8',
    chain_index: 44286,
    render_headline: 'Verified card payment — Stripe',
    render_subheadline: 'USD 520 via Mastercard ****8847 · treasury-agent',
    render_risk_label: 'low',
    instrument_id: 'inst_vc_5531',
    instrument_issuer: 'Lithic',
    card_authorization_id: 'auth_9zR3nQ7w',
    card_3ds_status: 'authenticated',
    merchant_screened_name: 'Stripe, Inc.',
    scope_evaluation: { within_scope: true, violations: [] },
    created_at: ago(58),
  },
  'evb_l2m3n4o5': {
    evidence_bundle_id: 'evb_l2m3n4o5',
    event_id: 'evt_l2m3n4o5',
    org_id: 'org_legaci_demo',
    intent_hash_algorithm: 'sha256',
    intent_hash_value: '1b0a9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b',
    intent_hash_canonical_fields: ['agent_id', 'payment_token', 'payment_amount', 'payment_to_address', 'timestamp'],
    authorization_type: 'policy-scoped-agent',
    authorized: false,
    authorizer: 'kontext-policy-engine-v2',
    authorization_scope: null,
    evaluated_at: ago(145),
    policy_trace: {
      decision: 'block',
      rules_evaluated: 4,
      passed_rules: ['ofac_clear'],
      failed_rules: ['amount_exceeds_daily_limit', 'destination_country_blocked'],
      warning_rules: [],
    },
    screening_provider: 'kontext-ofac-v1',
    screening_result: 'clear',
    screened_entity: '0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb',
    screening_screened_at: ago(145),
    exec_tx_hash: null,
    exec_chain: 'base',
    exec_observed_onchain: false,
    record_hash: '2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d',
    previous_record_hash: '1b0a9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b',
    chain_index: 44290,
    render_headline: 'Blocked: Daily limit exceeded',
    render_subheadline: 'USDC 150,000 blocked → RU · payment-agent-v1',
    render_risk_label: 'high',
    instrument_id: null,
    instrument_issuer: null,
    card_authorization_id: null,
    card_3ds_status: null,
    merchant_screened_name: null,
    scope_evaluation: null,
    created_at: ago(145),
  },
  'evb_s9t0u1v2': {
    // Reserve snapshot evidence
    evidence_bundle_id: 'evb_s9t0u1v2',
    event_id: 'evt_s9t0u1v2',
    org_id: 'org_legaci_demo',
    intent_hash_algorithm: 'sha256',
    intent_hash_value: '3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e',
    intent_hash_canonical_fields: ['agent_id', 'payment_token', 'payment_amount', 'payment_to_address', 'timestamp'],
    authorization_type: 'policy-scoped-agent',
    authorized: true,
    authorizer: 'kontext-policy-engine-v2',
    authorization_scope: 'stablecoin:base:USDC:4500',
    evaluated_at: ago(295),
    policy_trace: {
      decision: 'allow',
      rules_evaluated: 5,
      passed_rules: ['amount_within_daily_limit', 'ofac_clear', 'agent_trusted', 'reserve_reconciled', 'destination_allowlisted'],
      failed_rules: [],
      warning_rules: [],
    },
    screening_provider: 'kontext-ofac-v1',
    screening_result: 'clear',
    screened_entity: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
    screening_screened_at: ago(295),
    exec_tx_hash: '0xa2c4e6b8d0f2a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0a2',
    exec_chain: 'base',
    exec_observed_onchain: true,
    record_hash: '4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f',
    previous_record_hash: '3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e',
    chain_index: 44296,
    render_headline: 'Verified USDC payout + reserve check',
    render_subheadline: 'USDC 4,500 via Base · reserve reconciled · payment-agent-v1',
    render_risk_label: 'low',
    instrument_id: null,
    instrument_issuer: null,
    card_authorization_id: null,
    card_3ds_status: null,
    merchant_screened_name: null,
    scope_evaluation: null,
    reserve_snapshot: {
      token: 'USDC',
      chain: 'base',
      onChainSupply: '31420000000',
      publishedReserves: '31400000000',
      delta: '0.000637',
      reconciliationStatus: 'delta_within_tolerance',
      snapshotBlockNumber: 19842771,
      snapshotBlockHash: '0x3f9a8c71d4e2b6f8a1c3d5e9f2b4a6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4e6d8f0a2c4e6b8d0f2a4c6e8',
      timestamp: ago(295),
    },
    created_at: ago(295),
  },
};

// Fallback bundle for events not in the map
function makeFallbackBundle(event: VerificationEvent): EvidenceBundle {
  return {
    evidence_bundle_id: event.evidence_bundle_id,
    event_id: event.event_id,
    org_id: event.org_id,
    intent_hash_algorithm: 'sha256',
    intent_hash_value: Array.from({ length: 64 }, (_, i) => ((i * 13 + event.event_id.charCodeAt(i % event.event_id.length)) % 16).toString(16)).join(''),
    intent_hash_canonical_fields: ['agent_id', 'payment_token', 'payment_amount', 'payment_to_address', 'timestamp'],
    authorization_type: 'policy-scoped-agent',
    authorized: event.status !== 'blocked',
    authorizer: 'kontext-policy-engine-v2',
    authorization_scope: null,
    evaluated_at: event.created_at,
    policy_trace: {
      decision: event.status === 'blocked' ? 'block' : event.status === 'warning' ? 'warn' : 'allow',
      rules_evaluated: 3,
      passed_rules: event.status === 'blocked' ? [] : ['ofac_clear', 'agent_trusted'],
      failed_rules: event.status === 'blocked' ? event.policy_violations : [],
      warning_rules: event.status === 'warning' ? event.policy_warnings : [],
    },
    screening_provider: 'kontext-ofac-v1',
    screening_result: event.ofac_status === 'flagged' ? 'flagged' : 'clear',
    screened_entity: event.payment_to_address || event.agent_id,
    screening_screened_at: event.created_at,
    exec_tx_hash: event.payment_tx_hash,
    exec_chain: event.payment_chain,
    exec_observed_onchain: !!event.payment_tx_hash,
    record_hash: Array.from({ length: 64 }, (_, i) => ((i * 7 + event.event_id.charCodeAt(i % event.event_id.length)) % 16).toString(16)).join(''),
    previous_record_hash: Array.from({ length: 64 }, (_, i) => ((i * 11 + event.event_id.charCodeAt(i % event.event_id.length)) % 16).toString(16)).join(''),
    chain_index: 44280 + MOCK_EVENTS.findIndex(e => e.event_id === event.event_id),
    render_headline: event.status === 'blocked' ? `Blocked: ${event.policy_violations[0] ?? 'policy violation'}` : `Verified ${event.payment_token} payout`,
    render_subheadline: `${event.payment_token} ${parseFloat(event.payment_amount).toLocaleString()} · ${event.agent_id}`,
    render_risk_label: event.status === 'blocked' ? 'high' : event.status === 'warning' ? 'medium' : 'low',
    instrument_id: event.instrument_id,
    instrument_issuer: event.instrument_issuer,
    card_authorization_id: event.payment_card_authorization_id,
    card_3ds_status: event.payment_three_d_secure,
    merchant_screened_name: event.payment_merchant_name,
    scope_evaluation: event.instrument_id ? { within_scope: true, violations: [] } : null,
    created_at: event.created_at,
  };
}

// ---- agents -----------------------------------------------------------------

const MOCK_AGENTS: AgentData[] = [
  {
    agent_id: 'payment-agent-v1',
    agent_type: 'payment',
    actor_type: 'autonomous-agent',
    trust_score_avg: 92,
    payout_count_24h: 47,
    volume_24h_usd: '182400',
    anomaly_count_24h: 0,
    last_seen: ago(2),
    recent_events: [
      { event_id: 'evt_a1b2c3d4', status: 'verified', amount: '5200.00', token: 'USDC', created_at: ago(2) },
      { event_id: 'evt_i9j0k1l2', status: 'verified', amount: '3300.00', token: 'USDC', created_at: ago(88) },
      { event_id: 'evt_o5p6q7r8', status: 'verified', amount: '6700.00', token: 'USDC', created_at: ago(200) },
    ],
    authorized_chains: ['base', 'ethereum', 'polygon'],
    authorized_tokens: ['USDC', 'EURC'],
  },
  {
    agent_id: 'treasury-agent',
    agent_type: 'treasury',
    actor_type: 'autonomous-agent',
    trust_score_avg: 88,
    payout_count_24h: 19,
    volume_24h_usd: '318500',
    anomaly_count_24h: 1,
    last_seen: ago(22),
    recent_events: [
      { event_id: 'evt_d4e5f6g7', status: 'warning', amount: '48000.00', token: 'USDC', created_at: ago(22) },
      { event_id: 'evt_k1l2m3n4', status: 'verified', amount: '18000.00', token: 'USDC', created_at: ago(120) },
      { event_id: 'evt_r8s9t0u1', status: 'verified', amount: '9400.00', token: 'USDC', created_at: ago(270) },
    ],
    authorized_chains: ['base', 'ethereum', 'polygon', 'arbitrum'],
    authorized_tokens: ['USDC', 'EURC', 'USDT'],
  },
  {
    agent_id: 'defi-arb-bot',
    agent_type: 'trading',
    actor_type: 'autonomous-agent',
    trust_score_avg: 61,
    payout_count_24h: 83,
    volume_24h_usd: '94700',
    anomaly_count_24h: 3,
    last_seen: ago(44),
    recent_events: [
      { event_id: 'evt_f6g7h8i9', status: 'blocked', amount: '95000.00', token: 'USDC', created_at: ago(44) },
      { event_id: 'evt_j0k1l2m3', status: 'warning', amount: '7800.00', token: 'USDC', created_at: ago(105) },
      { event_id: 'evt_q7r8s9t0', status: 'warning', amount: '22000.00', token: 'USDC', created_at: ago(250) },
    ],
    authorized_chains: ['base', 'polygon'],
    authorized_tokens: ['USDC'],
  },
  {
    agent_id: 'compliance-monitor',
    agent_type: 'monitoring',
    actor_type: 'autonomous-agent',
    trust_score_avg: 99,
    payout_count_24h: 0,
    volume_24h_usd: '0',
    anomaly_count_24h: 0,
    last_seen: ago(5),
    recent_events: [],
    authorized_chains: ['base', 'ethereum', 'polygon', 'arbitrum', 'optimism'],
    authorized_tokens: ['USDC', 'EURC', 'USDT', 'DAI'],
  },
];

// ---- policies ---------------------------------------------------------------

const MOCK_POLICIES: PolicyData[] = [
  {
    policy_id: 'pol_amount_limit',
    name: 'Daily Amount Limit',
    type: 'amount',
    description: 'Max $100K per agent per 24h',
    enabled: true,
    violations_today: 1,
    impact_pct: 98.2,
  },
  {
    policy_id: 'pol_ofac_screen',
    name: 'OFAC Sanctions Screening',
    type: 'compliance',
    description: 'Screen all counterparties against SDN list',
    enabled: true,
    violations_today: 1,
    impact_pct: 100,
  },
  {
    policy_id: 'pol_travel_rule',
    name: 'Travel Rule',
    type: 'compliance',
    description: 'Collect originator/beneficiary for >$3K',
    enabled: true,
    violations_today: 0,
    impact_pct: 87.4,
  },
  {
    policy_id: 'pol_country_block',
    name: 'Country Blocklist',
    type: 'geo',
    description: 'Block OFAC-sanctioned jurisdictions (KP, RU, IR, CU, SY)',
    enabled: true,
    violations_today: 2,
    impact_pct: 99.8,
  },
  {
    policy_id: 'pol_card_scope',
    name: 'Card Merchant Scope',
    type: 'scope',
    description: 'Restrict virtual cards to approved MCC codes',
    enabled: true,
    violations_today: 0,
    impact_pct: 100,
  },
  {
    policy_id: 'pol_frequency',
    name: 'Frequency Limiter',
    type: 'rate',
    description: 'Max 100 payouts per agent per hour',
    enabled: false,
    violations_today: 0,
    impact_pct: 0,
  },
];

const MOCK_VIOLATIONS: PolicyViolation[] = [
  {
    event_id: 'evt_f6g7h8i9',
    created_at: ago(44),
    agent_id: 'defi-arb-bot',
    workflow: 'stablecoin-payment',
    amount: '95000.00',
    token: 'USDC',
    policy_decision: 'block',
    policy_violations: ['ofac_sanctions_match'],
    policy_warnings: [],
    applied_policy_ids: ['pol_ofac_screen', 'pol_country_block'],
    status: 'blocked',
  },
  {
    event_id: 'evt_l2m3n4o5',
    created_at: ago(145),
    agent_id: 'payment-agent-v1',
    workflow: 'stablecoin-payment',
    amount: '150000.00',
    token: 'USDC',
    policy_decision: 'block',
    policy_violations: ['amount_exceeds_daily_limit', 'destination_country_blocked'],
    policy_warnings: [],
    applied_policy_ids: ['pol_amount_limit', 'pol_country_block'],
    status: 'blocked',
  },
  {
    event_id: 'evt_d4e5f6g7',
    created_at: ago(22),
    agent_id: 'treasury-agent',
    workflow: 'stablecoin-payment',
    amount: '48000.00',
    token: 'USDC',
    policy_decision: 'warn',
    policy_violations: [],
    policy_warnings: ['amount_near_edd_threshold', 'new_destination_country'],
    applied_policy_ids: ['pol_amount_limit', 'pol_travel_rule'],
    status: 'warning',
  },
];

// ---- live event templates for subscribeMockEvents ---------------------------

const LIVE_TEMPLATES: Array<Omit<VerificationEvent, 'event_id' | 'created_at' | 'evidence_bundle_id'>> = [
  {
    org_id: 'org_legaci_demo', environment: 'production', status: 'verified',
    workflow: 'stablecoin-payment', agent_id: 'payment-agent-v1', agent_type: 'payment', actor_type: 'autonomous-agent',
    payment_tx_hash: '0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
    payment_chain: 'base', payment_rail: 'stablecoin', payment_token: 'USDC',
    payment_amount: '1250.00', payment_currency: 'USD', payment_usd_equivalent: '1250.00',
    payment_from_address: '0xd8da6bf26964af9d7eed9e03e53415d37aa96045',
    payment_to_address: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
    payment_destination_country: null, policy_decision: 'allow', policy_violations: [], policy_warnings: [],
    applied_policy_ids: ['pol_amount_limit', 'pol_ofac_screen'],
    ofac_status: 'clear', screening_provider: 'kontext-ofac-v1', trust_score: 93, trust_band: 'high',
    trust_reasons: ['established_agent'], coverage_status: 'covered',
    team_tag: null, business_unit_tag: null, instrument_id: null, instrument_type: null,
    instrument_network: null, instrument_issuer: null, instrument_scope: null,
    payment_card_last4: null, payment_merchant_category_code: null, payment_merchant_name: null,
    payment_merchant_country: null, payment_three_d_secure: null, payment_card_authorization_id: null,
  },
  {
    org_id: 'org_legaci_demo', environment: 'production', status: 'verified',
    workflow: 'stablecoin-payment', agent_id: 'treasury-agent', agent_type: 'treasury', actor_type: 'autonomous-agent',
    payment_tx_hash: '0x3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d',
    payment_chain: 'ethereum', payment_rail: 'stablecoin', payment_token: 'USDC',
    payment_amount: '8800.00', payment_currency: 'USD', payment_usd_equivalent: '8800.00',
    payment_from_address: '0xab5801a7d398351b8be11c439e05c5b3259aec9b',
    payment_to_address: '0x47ac0fb4f2d84898e4d9e7b4dab3c24507a6d503',
    payment_destination_country: 'US', policy_decision: 'allow', policy_violations: [], policy_warnings: [],
    applied_policy_ids: ['pol_amount_limit', 'pol_ofac_screen', 'pol_travel_rule'],
    ofac_status: 'clear', screening_provider: 'kontext-ofac-v1', trust_score: 90, trust_band: 'high',
    trust_reasons: ['established_agent', 'allowlisted_destination'], coverage_status: 'covered',
    team_tag: 'finance', business_unit_tag: null, instrument_id: null, instrument_type: null,
    instrument_network: null, instrument_issuer: null, instrument_scope: null,
    payment_card_last4: null, payment_merchant_category_code: null, payment_merchant_name: null,
    payment_merchant_country: null, payment_three_d_secure: null, payment_card_authorization_id: null,
  },
];

let _liveTemplateIdx = 0;

// ---- mock API functions -----------------------------------------------------

export async function getKpis(): Promise<KpiData> {
  return {
    org_id: 'org_legaci_demo',
    environment: 'production',
    as_of: new Date().toISOString(),
    verified_payouts_today: 1847,
    unverified_payouts_today: 3,
    org_trust_score: 91.2,
    sanctions_alerts_today: 1,
    policy_violations_today: 2,
    coverage_pct_7d: 99.8,
  };
}

export async function getVerificationEvents(
  filters: EventsFilters = {},
): Promise<{ events: VerificationEvent[]; next_cursor: string | null; count: number }> {
  let events = [...MOCK_EVENTS];

  if (filters.status) {
    events = events.filter((e) => e.status === filters.status);
  }
  if (filters.agent_id) {
    events = events.filter((e) => e.agent_id === filters.agent_id);
  }
  if (filters.chain) {
    events = events.filter((e) => e.payment_chain === filters.chain);
  }
  if (filters.rail) {
    events = events.filter((e) => e.payment_rail === filters.rail);
  }

  const limit = filters.limit ?? 20;
  const page = events.slice(0, limit);

  return {
    events: page,
    next_cursor: events.length > limit ? 'mock_cursor_next' : null,
    count: events.length,
  };
}

export async function getEvidence(eventId: string): Promise<EvidenceBundle> {
  // Look up by event_id across the map
  const bundleId = MOCK_EVENTS.find((e) => e.event_id === eventId)?.evidence_bundle_id;
  if (bundleId && EVIDENCE_MAP[bundleId]) {
    return EVIDENCE_MAP[bundleId] as EvidenceBundle;
  }
  // Fallback: generate a bundle from the event
  const event = MOCK_EVENTS.find((e) => e.event_id === eventId);
  if (event) return makeFallbackBundle(event);
  throw new Error(`Event ${eventId} not found`);
}

export async function getAgents(): Promise<{ agents: AgentData[]; count: number }> {
  return { agents: MOCK_AGENTS, count: MOCK_AGENTS.length };
}

export async function getPolicies(): Promise<{ policies: PolicyData[]; total_events_today: number }> {
  return { policies: MOCK_POLICIES, total_events_today: 1850 };
}

export async function getPolicyViolations(
  _limit = 20,
): Promise<{ violations: PolicyViolation[]; count: number }> {
  return { violations: MOCK_VIOLATIONS, count: MOCK_VIOLATIONS.length };
}

export async function createAuditExport(options: {
  format: string;
  date_range: { from: string; to: string };
}): Promise<{ export_id: string; status: string; event_count: number; data: unknown[] }> {
  const exportId = `exp_mock_${Date.now()}`;
  return {
    export_id: exportId,
    status: 'complete',
    event_count: MOCK_EVENTS.length,
    data: MOCK_EVENTS.map((e) => ({
      ...e,
      export_format: options.format,
      exported_at: new Date().toISOString(),
    })),
  };
}

/**
 * Subscribe to simulated live events. Calls callback with a new event every 8s.
 * Returns a cleanup function.
 */
export function subscribeMockEvents(
  onEvent: (event: VerificationEvent) => void,
): () => void {
  const id = setInterval(() => {
    const template = LIVE_TEMPLATES[_liveTemplateIdx % LIVE_TEMPLATES.length];
    _liveTemplateIdx++;
    const evtId = nextId();
    const event: VerificationEvent = {
      ...template,
      event_id: evtId,
      created_at: new Date().toISOString(),
      evidence_bundle_id: `evb_${evtId}`,
    };
    onEvent(event);
  }, 8_000);

  return () => clearInterval(id);
}

// Re-export types for convenience
export type {
  EventsFilters,
  KpiData,
  VerificationEvent,
  EvidenceBundle,
  AgentData,
  PolicyData,
  PolicyViolation,
} from './dashboard-api';
